### ISSUE TITLE
[Mac] Shift-M shortcut no longer works with Thunderbird 60.3.0 (64-bit)

### ISSUE THREAD

**Issue by dwt** [kewisch/quickmove-extension#1]
Not quite sure how I can provide more debugging info, but the shortcut seems to not any longer bring up the menu it did before.

Is there any better info I can provide?

**Comment by dwt** [comment]
@maintainers: ping? This is kinda making the plugin unusable for me on Mac. Is there a known workaround, any other info I can provide?

**Comment by dwt** [comment]
@maintainers - ping?

**Comment by lassana** [comment]
I also observe similar issue when opening the context menu of an item in the message list. The workaround is to right-click on the main toolbar (where the "Get Messages" button is), cancel it out and then right-click again on the message again.

**Comment by dwt** [comment]
This seems to have resolved itself with Thunderbird version 60.4.0, so I am closing this for now.
