### ISSUE TITLE
2.0.0.0pre1 identical folders 

### ISSUE THREAD

**Issue by mclaborn** [kewisch/quickmove-extension#10]
in 2.0.0pre1, when I click Shift + M, one of my email accounts shows 2 identically named folders. I don't think that there are 2 folders with the same name, but if there are there needs to be a way to tell them apart.

**Comment by kewisch** [comment]
Please see the release notes, this is a known issue. It could be that one of the folders is a subfolder of your archives folder. I'm considering the option to exclude these
