### ISSUE TITLE
Special character not decoded properly

### ISSUE THREAD

**Issue by tessarakt** [kewisch/quickmove-extension#100]
In the list of folders, special characters in the "path" of the folder are not decoded properly. However, they are decoded properly in the name of the folder itself.

E.g. "Behörden" is shown as "Beh&APY-rden" in the autocomplete results entry for a subfolder of it.

(version 2.0.1 on TB 115.2.2)

**Comment by kewisch** [comment]
Hmm strange, I wonder if this is a bug in the extensions API, since I don't do any special encoding. I had tested with a folder named ßßß and didn't experience any issues. Is it just ö causing issues, or generally?

**Comment by tessarakt** [comment]
Not sure if I made this sufficiently clear.

It's not about the name of the found folder itself, but about the parent folder.


Example:

I created äää > äöüß under my Inbox:
![grafik](https://github.com/kewisch/quickmove-extension/assets/2366126/0123d25d-1c1d-4f5e-925c-65b4fef3e92d)

This is shown as follows in the search results:

![grafik](https://github.com/kewisch/quickmove-extension/assets/2366126/9e556729-0487-4dc0-a472-aa82be1b0938)

**Comment by kewisch** [comment]
Thank you, can confirm. Took a shortcut to take the folder path instead of constructing the full name via the folder nodes, need to adjust a few things.
