### ISSUE TITLE
Recent folders not selectable in the Move/Copy popup

### ISSUE THREAD

**Issue by neliorc** [kewisch/quickmove-extension#101]
If I search for a folder in the Move/Copy popup, I can move emails normally. If I then repeat a Move operation without any search criteria and just use the recent folders list, the folders are not selectable/clickable.

Windows 11, Thunderbird 115.2.2 (64-bit)

**Comment by kewisch** [comment]
Do you get any error console messages when you try to click one of those folders?

**Comment by neliorc** [comment]
Yes! I do get a few errors:

`WebExtensions: NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIMsgCopyService.copyMessages]
    moveOrCopyMessages chrome://messenger/content/parent/ext-messages.js:644
    moveOrCopyMessages chrome://messenger/content/parent/ext-messages.js:643
    move chrome://messenger/content/parent/ext-messages.js:1287
    result resource://gre/modules/ExtensionParent.sys.mjs:1144
    withCallContextData resource://gre/modules/ExtensionParent.sys.mjs:627
    result resource://gre/modules/ExtensionParent.sys.mjs:1143
    withPendingBrowser resource://gre/modules/ExtensionParent.sys.mjs:637
    result resource://gre/modules/ExtensionParent.sys.mjs:1142
    callAndLog resource://gre/modules/ExtensionParent.sys.mjs:1095
    recvAPICall resource://gre/modules/ExtensionParent.sys.mjs:1141
    _recv resource://gre/modules/ConduitsChild.sys.mjs:77
    receiveMessage resource://gre/modules/ConduitsParent.sys.mjs:453
    JSActor query*_send resource://gre/modules/ConduitsChild.sys.mjs:61
    _send resource://gre/modules/ConduitsChild.sys.mjs:111
    callParentAsyncFunction resource://gre/modules/ExtensionChild.sys.mjs:911
    callAsyncFunction resource://gre/modules/ExtensionChild.sys.mjs:630
    stub resource://gre/modules/Schemas.sys.mjs:2897
    op moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/background.js:29
    promise callback*processSelectedMessages moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/background.js:29
    async* moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/background.js:60
    raw resource://gre/modules/ExtensionCommon.sys.mjs:2762
    wrapResponse resource://gre/modules/ExtensionChild.sys.mjs:214
    responses resource://gre/modules/ExtensionChild.sys.mjs:183
    emit resource://gre/modules/ExtensionChild.sys.mjs:183
    recvRuntimeMessage resource://gre/modules/ExtensionChild.sys.mjs:383
    _recv resource://gre/modules/ConduitsChild.sys.mjs:77
    receiveMessage resource://gre/modules/ConduitsChild.sys.mjs:189
    JSActor query*_send resource://gre/modules/ConduitsChild.sys.mjs:59
    _send resource://gre/modules/ConduitsParent.sys.mjs:288
    promises resource://gre/modules/ConduitsParent.sys.mjs:328
    _cast resource://gre/modules/ConduitsParent.sys.mjs:328
    recvRuntimeMessage resource://gre/modules/ExtensionParent.sys.mjs:350
    _recv resource://gre/modules/ConduitsChild.sys.mjs:77
    receiveMessage resource://gre/modules/ConduitsParent.sys.mjs:453
    JSActor query*_send resource://gre/modules/ConduitsChild.sys.mjs:59
    _send resource://gre/modules/ConduitsChild.sys.mjs:111
    sendRuntimeMessage resource://gre/modules/ExtensionChild.sys.mjs:350
    sendMessage chrome://extensions/content/child/ext-runtime.js:73
    callAsyncFunction resource://gre/modules/ExtensionCommon.sys.mjs:1156
    callAsyncFunction resource://gre/modules/ExtensionChild.sys.mjs:737
    callAndLog resource://gre/modules/ExtensionChild.sys.mjs:708
    callAsyncFunction resource://gre/modules/ExtensionChild.sys.mjs:736
    stub resource://gre/modules/Schemas.sys.mjs:2897
    load moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/popup/popup.js:60
    dispatchSelect moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/popup/folderlist.js:316
    folderListClick moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/popup/folderlist.js:309
    connectedCallback moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/popup/folderlist.js:223
    <anonymous> moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/popup/folderlist.js:489
[ext-messages.js:670](chrome://messenger/content/parent/ext-messages.js)

Uncaught (in promise) Error: Error moving message: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIMsgCopyService.copyMessages]
    load moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/popup/popup.js:60
    dispatchSelect moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/popup/folderlist.js:316
    folderListClick moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/popup/folderlist.js:309
    connectedCallback moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/popup/folderlist.js:223
    <anonymous> moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/popup/folderlist.js:489
undefined
    load moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/popup/popup.js:66
    AsyncFunctionThrow self-hosted:856
    (Async: async)
    dispatchSelect moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/popup/folderlist.js:316
    folderListClick moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/popup/folderlist.js:309
    (Async: EventListener.handleEvent)
    connectedCallback moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/popup/folderlist.js:223
    <anonymous> moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/popup/folderlist.js:489

Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
[popup.js:76](moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/popup/popup.js)
    unload moz-extension://ef4a14da-8b50-4b19-8030-88decf1e04d7/popup/popup.js:76

​`

**Comment by kewisch** [comment]
Uh, ok, that is interesting. It appears a value is being passed to the move function which is not correct. Can you try version 2.6.5 posted in #88 and get back here? I've made a few fixes, maybe we are lucky and it will just work.

Otherwise I'd need you to do some debugging to find out what is being passed to the browser.messages.move() function. I can't reproduce this locally.

**Comment by neliorc** [comment]
I've installed 2.6.9 and now it doesn't seem to remember any recent folders. It just shows the Inbox folder for all my accounts. And, strangely, some of them appear multiple times.

**Comment by kewisch** [comment]
Is this still an issue with 2.9.2 ? I might have fixed this in the meanwhile

**Comment by neliorc** [comment]
It seems it's fixed, yes! Thank you!
