### ISSUE TITLE
Conflicting shortcuts in KDE

### ISSUE THREAD

**Issue by rigow** [kewisch/quickmove-extension#105]
While using KDE, the shortcut CTRL+SHIFT+M is used as a global shortcut in KWin to toggle the "do not disturb".  This has the effect that the shortcut for quickmove in thunderbird does not work. One has to click on the icon.

As long as this shortcut for do not disturb exists, quickmove will refuse that shortcut when editing shortcuts manually. The shortcut CTRL+ALT+M worked. Then I removed the global shortcut in KDE Kwin and it accepted CTRL+SHIFT+M again and I've set it to this value. Now it works as advertised. 

When CTRL+SHIFT+M worked, it did not open the popup, but just repeated the action and moved the selected email to  the last destination. I will report that in the other issue. IF I select CTRL+ALT+M as the shortcut to move things, the popup opens and it does everything normally. 

So IF the shortcuts need to be changed, the selection of those shortcuts need to be tested for conflicts IMHO.

**Comment by kewisch** [comment]
Shortcuts are super hard to make unique, so I probably won't be able to please every OS. See #88, I'm moving to Ctrl+Shift+N on Windows/Linux. Can you test the version and comment there as needed?
