### ISSUE TITLE
Search with multiple strings

### ISSUE THREAD

**Issue by l8com** [kewisch/quickmove-extension#109]
Space separated strings should be connected as AND search term. 
Currently any string is used as a search term to occur in the parth. This is continued with any special character such as space. Therefore it is not possible to define two strings that should both occur in the path.

**Comment by kewisch** [comment]
This seems reasonable. Indeed it is a simple substring match at the moment.

**Comment by kewisch** [comment]
Fixed in 2903c78a0914354c8a4c53a38d5bd1c98fadbfe1 and will release as soon as #88 works reasonably well :-)

**Comment by l8com** [comment]
Works! Much better now! Thank you!
Using Windows 11, TB 115.3.1, Quickmove 2.6.9
