### ISSUE TITLE
After removing an attachment, moving a message does not work. 

### ISSUE THREAD

**Issue by tessarakt** [kewisch/quickmove-extension#11]
Version: 2.0.0pre1

Steps to reproduce:

1. Select a message with attachment.
2. Detach an attachment.
3. Press Shift-M, select a folder and confirm.

Expected result: Message is moved to that folder.
Actual result: Nothing happens.

I tried various things to recover:
- Select a different message and then the same one again. Repeat step 3. => Still nothing happens.
- Restart Thunderbird, repeat steps 1 and 3 => Message is moved.

I also tried moving a message with Drag&Drop after detaching an attachment. That works just fine.

**Comment by kewisch** [comment]
This puzzles me a bit, not sure what the attachment would do so I am guessing this is a Thunderbird issue. Can you provide console messages?

**Comment by tessarakt** [comment]
I saw this:

**Comment by tessarakt** [comment]
And also:

{
  "from": "server1.conn0.child20/context18",
  "error": "unknownError",
  "message": "error occurred while processing 'sources: TypeError: can't access dead object\nStack: webExtensionTargetPrototype._allowSource@resource://devtools/server/actors/targets/webextension.js:323:1\nTabSources/this.allowSource@resource://devtools/server/actors/utils/TabSources.js:35:39\n_addSource@resource://devtools/server/actors/thread.js:1792:23\nonSources@resource://devtools/server/actors/thread.js:1212:12\nonPacket@resource://devtools/server/main.js:1395:58\nreceiveMessage@resource://devtools/shared/transport/child-transport.js:66:16\nLine: 323, column: 1"
}

**Comment by kewisch** [comment]
Is this still an issue in v2 final and Thunderbird 115?

**Comment by tessarakt** [comment]
Just tested it, works fine.
