### ISSUE TITLE
Does not work when viewing a message in a tab

### ISSUE THREAD

**Issue by EJR1501** [kewisch/quickmove-extension#110]
Previously, I could press shift M either in list view or while reading a message in a tab. Now, in Thunderbird 115.3.1, pressing shift M in list view still works, albeit slowly, but trying to use it in message view is riddled with defects, and control shift M moves the message to the last (alphabetically) subfolder of my inbox, instead of asking me where I want to move it to!

**Comment by kewisch** [comment]
The keyboard shortcut is indeed an issue, see #88. I believe I also fixed some issues related to message view. Can you try the version I linked in a comment in #88?

**Comment by EJR1501** [comment]
Thank you Philipp, but that version is even worse:

In list view or in message view, I press control + shift + V (the shortcut I have assigned to move), the pop-up does show up, but not the folder list. I start typing the folder name, and nothing comes up.

Kind regards,

Esther
--
Get an instant quote for computer services and support.
http://www.thebluelizard.co.uk/quotecalc.php
The Blue Lizard Ltd. Studio G6, Building OB, East 10 Enterprise Park, London E10 7DQ.
Tel: 020 7184 9800
Reg. Nº 4159571. VAT Reg. Nº GB 778140608.

**Comment by kewisch** [comment]
Can you try version 2.6.5? I've tested this again with the message display window and found some issues that should now be fixed.

**Comment by EJR1501** [comment]
Amazing, thank you very much, Phillip. This version works as I need it to, hurrah!

Esther
--
Get an instant quote for computer services and support.
http://www.thebluelizard.co.uk/quotecalc.php
The Blue Lizard Ltd. Studio G6, Building OB, East 10 Enterprise Park, London E10 7DQ.
Tel: 020 7184 9800
Reg. Nº 4159571. VAT Reg. Nº GB 778140608.

**Comment by EJR1501** [comment]
I’m sorry Phillip, I spoke too soon: when viewing a message in a tab, using version 2.6.5, pressing shift  + M (my chosen shortcut) does display the folder list, and does find the correct folder if I type the first few letters of the folder name, and pressing the down arrow does select the folder, but pressing the enter key at that point does nothing.

It works fine in list view, but not when viewing a message in a tab.

Sorry for the bad news!

Esther
--
Get an instant quote for computer services and support.
http://www.thebluelizard.co.uk/quotecalc.php
The Blue Lizard Ltd. Studio G6, Building OB, East 10 Enterprise Park, London E10 7DQ.
Tel: 020 7184 9800
Reg. Nº 4159571. VAT Reg. Nº GB 778140608.

From: Esther Regenwetter
Sent: 09 October 2023 19:00
To: 'kewisch/quickmove-extension' ***@***.***>; kewisch/quickmove-extension ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [kewisch/quickmove-extension] Does not work when viewing a message in a tab (Issue #110)

Amazing, thank you very much, Phillip. This version works as I need it to, hurrah!

Esther
--
Get an instant quote for computer services and support.
http://www.thebluelizard.co.uk/quotecalc.php
The Blue Lizard Ltd. Studio G6, Building OB, East 10 Enterprise Park, London E10 7DQ.
Tel: 020 7184 9800
Reg. Nº 4159571. VAT Reg. Nº GB 778140608.

**Comment by kewisch** [comment]
Can confirm. Will take a look. Thanks for testing!

**Comment by kewisch** [comment]
Fixed in c99db42416a3f8f6aeb9155d18d11c0427cebad5 now, thanks!

**Comment by EJR1501** [comment]
Thank you very much Philipp, what a relief to have this working again!

Esther
--
Get an instant quote for computer services and support.
http://www.thebluelizard.co.uk/quotecalc.php
The Blue Lizard Ltd. Studio G6, Building OB, East 10 Enterprise Park, London E10 7DQ.
Tel: 020 7184 9800
Reg. Nº 4159571. VAT Reg. Nº GB 778140608.
