### ISSUE TITLE
Ctrl+Shift+M doesn't work as expected

### ISSUE THREAD

**Issue by camfarnell** [kewisch/quickmove-extension#111]
Ubuntu 22.04.3 LTS.  With option "Embracing change." and having made no other changes then Ctrl+Shift+M doesn't pop up the Move dialog but instead just moves the selected message to the most recent folder (that is, the folder that is at the top of the list if I had called up the Move dialog using the Quick Move button).

With option "Change is hard." and no other changes then Shift+M calls up the Move dialog as expected but Ctrl+Shift+M works as described as above.

**Comment by kewisch** [comment]
Hey, please head over to #88 which has a fixed version. Releasing soon!
