### ISSUE TITLE
Search window bouncing

### ISSUE THREAD

**Issue by mclaborn** [kewisch/quickmove-extension#113]
Using 2.6.8 on Ubuntu 20.04
See attached screen shots. 
![a](https://github.com/kewisch/quickmove-extension/assets/1437059/15826261-7d69-4a13-afda-373053eba489)
![b](https://github.com/kewisch/quickmove-extension/assets/1437059/90e3f694-655a-4a11-b69b-3bf75a4d7a19)
When I invoke Quick Move on the selected message (Ctrl + M) the search windows flashes very briefly to the position in b.png but then settles in the position shown in a.png. This initial flash doesn't bother me (much). 

After I type some search letters it moves to position shown in b.png. 

I assume that the initial position is because there is not enough room to display at the bottom so it moves to the top, and that makes sense. 

My preference would be to not have the window move after the initial positioning. In this example, it would stay at the position shown in a.png.

**Comment by kewisch** [comment]
Hmm interesting. I'm not sure what to do here aside from maybe making the box a fixed 600px high, which will keep it at one side, but also waste space if there aren't as many folders. I unfortunately can't control what side it is on.

**Comment by mclaborn** [comment]
I would be fine with the fixed height. The wasted space won't bother me since when that window is showing that's the only thing I'm looking at.

**Comment by kewisch** [comment]
Alright, let's try it out for a release or two and see who complains :)

Fixed in 314d8b6fb17c89179eac1cb463f00c4411aa6ea2
