### ISSUE TITLE
CTRL + SHIFT + M shortcut not working / conflict with Thunderbird

### ISSUE THREAD

**Issue by ArtCodesArt** [kewisch/quickmove-extension#114]
QuickMove version: 2.0.1
Thunderbird version: 115.3.1
Linux Mint 21 x86_64

**Background**
1. Upgraded QuickMove and Thunderbird
2. Using default shortcuts (i.e. no changes made)
3. The CTRL + SHIFT + M shortcut does not bring up/display the pop-up.
4. It appears the **default** [Thunderbird CTRL + SHIFT + M](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-thunderbird?redirectslug=keyboard-shortcuts&redirectlocale=en-US) conflicts with the **default** QuickMove shortcut

Thunderbird default shortcut:
![Thunderbird default ctrl sfit m](https://github.com/kewisch/quickmove-extension/assets/43051000/e84c40c5-dca4-4852-b6b2-34fb2d7548a9)

QuickMove shortcut
![QuickMove default shortcut](https://github.com/kewisch/quickmove-extension/assets/43051000/3559290d-cd20-4900-a57c-dc1d174955f7)

**Comment by kewisch** [comment]
Hey, thanks for filing the issue. Please see #88 for details, a new version 2.6.9 is attached to the end.
