### ISSUE TITLE
New Shortcuts not working on Linux Mint

### ISSUE THREAD

**Issue by jastram** [kewisch/quickmove-extension#115]
Howdy,

Thanks for this great addon — I used it for ages and cannot think living without it!

I am on Linux Mint, where the new shortcuts don't seem to work:

- Ctrl-Shift-C works fine
- Ctrl-Shift-G opens "Find in Page"
- Ctrl-Shift-M moves the message, but without opening the folder selction dialog. I *think* it's picking the first folder from the Quick Folder selection list.

According to the Extension Shortcuts Manager, I don't have any conflicting Shortcuts.

Thanks for helping! Let me know if I can contribute some debugging information.

OS: Linux Mint21 5.15.0-86-generic #96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Thunderbird: 115.3.1

Best,
- Michael

**Comment by kewisch** [comment]
Hi Michael, this is a known issue which will be "fixed" in the upcoming 2.6.9. Please see #88 for a pre-release version, very bottom. Unfortunately we'll have to pick another shortcut.

**Comment by jastram** [comment]
Oops, thank you for the note! I searched beforehand to prevent filing a duplicate, but missed #88, because it was already closed (for obvious reasons).
