### ISSUE TITLE
Ctrl + Shift + M doesn't work in latest Thunderbird 115.3.2

### ISSUE THREAD

**Issue by miles-404** [kewisch/quickmove-extension#117]
Just updated to Thunderbird 115.3.2.  Shift + M didn't work, I saw it's no longer allowed and replaced by Ctrl + Shift + M, but that doesn't work, no dialog appears, in fact it just makes the message "disappear" (it comes back with Ctrl + Z). I absolutely love this extension and I wouldn't be using Thunderbird if it doesn't work.  Is there any chance this could be fixed?  Also, Ctrl + Shift + G launches Thunderbird's search in message, it doesn't open the "go to" dialog.

**Comment by dapimentel** [comment]
This is a persistent problem. The Ctrl+Shift+M shortcut just performs the T-Bird action of "Move to <folder> Again" that exists on the "Message" menu. So what about some other options?
1. The Ctrl+M is a shortcut already reserved by T-Bird.
2. The Alt+Shift+M shortcut is also reserved by T-Bird (it activates the Message menu itself. Unfortunately, Quick Move Filter does not warn of this conflict.
3. Finally, Ctrl+Alt+M works. Perhaps this should be the documented default for Quick Move Filter.

**Comment by kewisch** [comment]
Hi. Are you on quickmove 2.7.0 yet? The keyboard shortcuts have changed once again and should now default to Ctrl+Shift+N.

**Comment by dapimentel** [comment]
Thanks for the heads up. I see it was released to the https://addons.thunderbird.net/en-US/thunderbird/addon/quick-folder-move/versions/ yesterday. I am using it now.

**Comment by kewisch** [comment]
Great, thanks! Glad it is working now.
