### ISSUE TITLE
Folders not grouping under account

### ISSUE THREAD

**Issue by mclaborn** [kewisch/quickmove-extension#118]
TB 115.3.1 on Ubuntu 20.04
See screen shot below.  The folders for account MM are not grouped together, but show up several different times. I have Default Folders = Recent Folders. I suspect it is showing the folders in most recent order, but it might make sense to group them by account anyway? That would allow more recent folders to show in the same space. 

![grouping](https://github.com/kewisch/quickmove-extension/assets/1437059/4bcba649-a8da-4adc-97d6-97acdb479e67)

**Comment by kewisch** [comment]
Ah yes, good point. The logic to show a new account heading is fairly simple. Thanks for filing!

**Comment by kewisch** [comment]
Fixed in 9be45b242f1b6e0368a6d8fc73cdce072fb54d1e

**Comment by mclaborn** [comment]
I'm loving this, thanks.
