### ISSUE TITLE
Keyboard shortcuts no longer working in Thunderbird 115.3.1 (64-bit)

### ISSUE THREAD

**Issue by MRus00** [kewisch/quickmove-extension#119]
Hi -- Thunderbird recently upgraded for me and first thing I notice is that the keyboard shortcuts (which is all I use for speed) no longer work. As a result quickmove no longer work :-(. Is this feature known? Is there a resolution planned? Many thanks.

**Comment by kewisch** [comment]
Hey. Did you get a message when the new version installed? There are some instructions on why the keyboard shortcuts have changed and what the new ones are.

**Comment by benlundmaine** [comment]
I have the same problem with the new version.  115.3.2 seemed to break it again.

**Comment by kewisch** [comment]
Which keyboard shortcuts are you currently using?

**Comment by infinitelyintrigued** [comment]
Hi, I just want to share my experience. I re-mapped to Ctrl+Alt+M according to the "Upgrade if your shortcuts aren't working. New: Ctrl+Shift+N" post now works fine. (I also use CardBook.).

The only issue I'm having right now is that I can only search for top-level folders. (I'm using Thunderbird 115.3.2 and Quick Folder Move 2.7.0.) I'm planning to submit this issue.

**Comment by kewisch** [comment]
Alright, I'm going to go ahead and close this issue. @MRus00 if changing the shortcuts doesn't work for you please feel free to comment or open a new issue.
