### ISSUE TITLE
Tooltip shows encoded folder name for special character

### ISSUE THREAD

**Issue by tessarakt** [kewisch/quickmove-extension#12]
Version: 2.0.0pre1

1. Press Shift-M
2. Enter a folder name which contains a special character (like ß).
  => The folder name is shown properly (with the special character).
3. Hover the mouse.

Actual result: Tooltip is shown, but &AN8- is shown instead of ß.
Expected result: The full path should also show the special character properly.

**Comment by gfrenoy** [comment]
Looks like IMAP UTF-7.  Maybe this can help : https://github.com/emailjs/emailjs-utf7.

**Comment by kewisch** [comment]
The tooltip was a hack, definitely a valid issue. I'm going to get the decoded name from Thunderbird, it just wasn't as straightforward.

**Comment by gfrenoy** [comment]
Thanks Philipp, I searched a bit to understand how to get the decoded name from Thunderbird but ... I do confirm, it's not straightforward :-/

If you can give me some guidance : documentation to read, article to find inspiration, .. whatever, I'll be happy to investigate further, propose pull requests and hopefully help !

**Comment by kewisch** [comment]
The way I had planned to do it was walk up the chain of folders and get those names. The data is already there, it just wasn't pretty or performant to get to it. The `name` property the api delivers should already be decoded.

**Comment by kewisch** [comment]
See also #14 which will require walking up the chain as well, and is likely a better solution than the tooltip. I'm thinking it might make sense to keep previous behavior where the folder is only shown if there are duplicate names.

**Comment by gfrenoy** [comment]
I'm using #14 for a couple weeks now and I don't want to hear about tooltip anymore ... It's very slow to wait for the tooltip to show ... Having the information shown, in a greyed color that does not attract your eyes.  Unless you need to look at it to resolve any conflict that you would have by looking at the similar folders given by your search.

**Comment by kewisch** [comment]
I've tested v2 final with ß now and it seems to work fine. We also have options for full path, if anything is missing please file a new issue.
