### ISSUE TITLE
Folder list to not show saved search folders

### ISSUE THREAD

**Issue by kumarpranay** [kewisch/quickmove-extension#121]
Current the folder list shows Saved Search folders. Obviously we cannot move messages to these virtual folders and these should be excluded from the folder list.

**Comment by kewisch** [comment]
Good point. I wish I had a simple filter to query for any notion of "writable", but that would require some upstream work. I'll exclude virtual folders as well, this should be easy to do (and could actually be a good first bug!)

**Comment by kewisch** [comment]
It turns out I can't filter these out :-( 

I've filed this one https://bugzilla.mozilla.org/show_bug.cgi?id=1859038

**Comment by kewisch** [comment]
And this one: https://bugzilla.mozilla.org/show_bug.cgi?id=1859040 to understand if a folder is writable

**Comment by kewisch** [comment]
Then let's monitor https://bugzilla.mozilla.org/show_bug.cgi?id=1529791

**Comment by kewisch** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1520425 will be ready for Thunderbird 121, so we can take care of this in the next update.

**Comment by kewisch** [comment]
This works now in the upcoming 3.0 in Thunderbird 128. The API is available now :)
