### ISSUE TITLE
Archive Folders Not Displayed

### ISSUE THREAD

**Issue by benlundmaine** [kewisch/quickmove-extension#123]
TB 115.3.2 appears to have broken this so that the complete folder list is no longer displayed.  I have a folder tree under "Archive," and none of them are available as a destination.  It is as if they do not exist.  Thanks!

**Comment by Zolixguru** [comment]
![screenshot](https://github.com/kewisch/quickmove-extension/assets/79288601/4eb89920-d555-4e18-9995-09b5a579e1db)

this helps?
in the options, there is a setting about that, if I'm right

**Comment by kewisch** [comment]
Indeed, I've hidden archive folders by default. Could have been mentioned in the upgrade notice, but too late for that now :)

Thanks for checking, and than you @Zolixguru for taking the time to respond with a screenshot!
