### ISSUE TITLE
Weird "next tab" behavior to reach Goto tab with arrows

### ISSUE THREAD

**Issue by doegox** [kewisch/quickmove-extension#124]
Version 2.7.0

Symptoms:

* From main TB screen, reading a mail, press ctrl+shift+N
* Focus is on Move (tab 1)
* Press Right arrow key
* Focus is on Copy (tab 2)
* Press Right arrow key
* Focus is on Tag (tab 4!!)
* Press Right arrow key
* Focus is on Goto (tab 3!!)

**Comment by kewisch** [comment]
Huh, I was experiencing this while testing and thought I fixed it. Will take another look.

**Comment by kewisch** [comment]
Can you double check you have 2.7.0? For that version the order is move,copy,goto,tag: https://github.com/kewisch/quickmove-extension/blob/v2.7.0/src/popup/popup.html#L25

**Comment by doegox** [comment]
![image](https://github.com/kewisch/quickmove-extension/assets/60773/187208a8-02b4-4311-bb01-4aa6419b1aaa)
:man_shrugging:

**Comment by doegox** [comment]
Hmm wait, there is a different behavior depending on how the popup is raised:

* if I click on the Quick Move button then use arrows, it behaves as expected
* If I use ctrl-shift-N, then use arrows, then it's buggy

**Comment by doegox** [comment]
The bug disappears when I do
```diff
diff --git a/src/background.js b/src/background.js
index 6d35860..e20efd4 100644
--- a/src/background.js
+++ b/src/background.js
@@ -129,7 +129,7 @@ browser.runtime.onInstalled.addListener(({ reason, previousVersion }) => {
 
 browser.commands.onCommand.addListener(async (name) => {
   let popupOrder = [browser.messageDisplayAction, browser.browserAction];
-  let popupUrl =`/popup/popup.html?action=${name}&allowed=move,copy,tag,goto`;
+  let popupUrl =`/popup/popup.html?action=${name}&allowed=move,copy,goto,tag`;
   if (name == "goto") {
     popupOrder = popupOrder.reverse();
   }
```

Note that there is also a "move,copy,tag,goto" in src/popup/popup.js L51 but I didn't have to change it.

**Comment by kewisch** [comment]
Indeed, good catch, thank you for debugging! The code is still a bit fragile, but I'm taking the easy path today. Took care in a8bafcd1ced2e02516d17fc45dcf0a2b4ab13eba
