### ISSUE TITLE
some folders are not referenced anymore

### ISSUE THREAD

**Issue by pylouis** [kewisch/quickmove-extension#125]
Dear Philipp Kewish,
thanks for extension quickmove.
I am using it a lot since a couple of years. With the recent upgrade, some folders are not show/suggested anymore. Strange. They are in an 'ARchives' box in some remote account. It was working very well previously.
Best regards,

**Comment by kewisch** [comment]
Hey, can you check the add-on options? Archive folders are now hidden by default, but you can enable them again.

**Comment by pylouis** [comment]
ok, thanks. It works now. BUT, the situation was inhomogenous for archives, it was not working for some folders while working for some other folders in archives too. Updaing the options worked. Many thanks for quick and efficient reply.

**Comment by kewisch** [comment]
Interesting, that might be worth investigating. Can you try to find out if there is a pattern as to what archive folders are still visible if the skip archive checkbox is enabled? Could it maybe be that these are folders that also have one with the same name outside of the archive structure?

**Comment by pylouis** [comment]
Hi, I checked. Yes indeed. There are folders called 'ARCHIVES' or starting with archives, but without the archives status (logo is different). Thus your option is working well. 
Thank you.

**Comment by kewisch** [comment]
Thanks for checking! I believe there were some add-ons that manipulate folder flags in a way that you could mark those other folders as archive folders as well.
