### ISSUE TITLE
Don't show message's current folder in Move mode

### ISSUE THREAD

**Issue by mclaborn** [kewisch/quickmove-extension#126]
When using Quick Move to Move a message, don't show in the list the folder in which the message current resides. I see this most often when a message has recently arrived and I use QM to move it.

**Comment by kewisch** [comment]
I ran into this as well but haven't gotten around to fixing it. Do you want to take a stab at it and send a PR?

**Comment by mclaborn** [comment]
OK. Not sure when I'll get to it.

**Comment by kewisch** [comment]
Much appreciated!

**Comment by kewisch** [comment]
[quick_folder_move-2.9.3pre.zip](https://github.com/user-attachments/files/17869214/quick_folder_move-2.9.3pre.zip)
Does this work for you?
