### ISSUE TITLE
searching for substring of "gmail" results in weird display

### ISSUE THREAD

**Issue by mclaborn** [kewisch/quickmove-extension#129]
When you search for a substring of "gmail" (e.g. "ma") you can get some folders that visually don't match, or the folder name is blank (I hope this isn't a bug in my PR). It's because the display omits folders with "[" which applies to folders like [Gmail]. 

Not sure what the best solution is.

**Comment by kewisch** [comment]
Do you have a screenshot? I don't see this happening as is, if I search for "ma" I get a bunch of [Gmail] folders.
