### ISSUE TITLE
right clock quick move

### ISSUE THREAD

**Issue by log-blip** [kewisch/quickmove-extension#131]
Before the latest upgrade it was possible to right click a message a type the name of the folder to move the message to.
This option was very intuitive and an eficient way to move a message. Now you need to move the mouse to a button in order to type the destination forlder. Right clicking was a better option.

**Comment by rmmbr** [comment]
@log-blip : Why do you don't use keyborad shortcuts for moving messages? You only have to remember one or two and it's possible to choose your prefered ones. It's quick and convenient.

**Comment by log-blip** [comment]
Hi @rmmbr ,

I don't think TB shortcut allow you to type the destination folder.
The ctrl+shift+N conflicts with the 'New message' shortcut. Shortcuts appears to be an issue with other users too. It is yet another shortcut to remember and typing ctrl+shift+N single-handedly can be a feat to some.

Right-click is just too simple to ignore.

**Comment by rmmbr** [comment]
@log-blip : For using of your prefered shortcuts on your own system see [https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox). Moving without mouse is possible and very effective ...

**Comment by log-blip** [comment]
Hi @rmmbr, I appreciatte that. I'm a heavy user of shortcuts on my main productity tools, and I'm all familiar with them. But you will also appreciatte explaining shortcuts to less inclined people can  be a challange.

As mentioned, right click is just too simple and I can't see a reason to take it out intencionally.

Rgs.

**Comment by sommer-gei** [comment]
Hey!

I also wanna say that I really miss the (old) right-click option to move around a single email or a bunch of (selected) emails.
And I wanna mention #133, which IMHO supports this request, too.

Please bring back the right-click option, if it's possible. (I couldn't find any information why it vanished.)

KR

**Comment by kewisch** [comment]
The upgrade instructions had some details why it isn't possible. The old approach in the context menu made massive use of platform internals. The new version was largely rewritten and uses the new extensions API, which doesn't allow manipulating the context menu in the same way.

I could add a context menu item that opens the popup, but then again folks could just click on the popup? Let me know if that would be helpful.

**Comment by kewisch** [comment]
[quick_folder_move-contextmenu.zip](https://github.com/kewisch/quickmove-extension/files/14016403/quick_folder_move-contextmenu.zip)
Here is a preview version with the context menu item. It feels kind of out of place to me since it just opens the thing you could otherwise also click on, but it would add a context menu item. I'm currently skeptical I should commit these changes, so I'll need someone to convince me otherwise :)

**Comment by rmmbr** [comment]
One vote from me against the commit ...
