### ISSUE TITLE
Problem with key movement over Move / Copy / Goto / Tag 

### ISSUE THREAD

**Issue by KC-T** [kewisch/quickmove-extension#132]
The options are in the order of Move / Copy / Tag / Goto when the key is moved to the right instead of the displayed order. This needs correction.

The key will stop at Goto when moved to the right and at Move when moved to the left. It is preferred to be able to cycle around.

I have used Atl-B / C / D for Move / Copy / Goto instead of Crtl-Shift-N. Using Alt-C to call the pop-up window and then move the key around may as well be easy because I need to remember "C" only to match the middle option. It is a bit difficult to remember "B" for Move and "D" for Goto.

**Comment by mickoz** [comment]
+1

It definitely needs to follow visual order, else it is counter-intuitive and I don't know what advantage the current behavior will give.

I have also thought about cycling.  It sures will allow some faster workflow, but won't allow to press totally left or totally right and expect it to stop.  But chance are there will be more advantages to being able to cycle through the options and it is intuitive.

P.S., As for the shortcut, I am curious (on Windows), why we had to diss SHIFT+M which was very intuitive, I am getting used to CTRL+SHIFT+N, but the "N" mean nothing to me... "M" would be better, but it is reserved for "move again to" it seems (and I don't know if we can overwrite default Thunderbird Shortcut).  I rarely use it personally and if it was replaced for QuickMove, then I can still move again easily if I really want to as it display last moved folder on top.

**Comment by kewisch** [comment]
Yep, noticed this as well, thanks! The tab order will be fixed in 2.8.0. 

I really loved Shift+M, but there are some limitations in the new extensions API that keyboard shortcuts need to have a certain amount of modifiers. This is a Firefox restriction that carries on to Thunderbird, Thunderbird developers would have to make some extensions API improvements to allow more shortcuts. #88 has the whole story.
