### ISSUE TITLE
Mouse moving over dropdown Quick Move menu removes focus leading to typeahead disaster

### ISSUE THREAD

**Issue by Olghn** [kewisch/quickmove-extension#133]
I have struggled to adapt my muscle menu to use the new "Quick Move" button instead of right-click on a message I want to move.

Then I found I was repeatedly messing up my mailbox when the folder name I typed (to move the message to) was instead interpreted as a series of keyboard shortcuts by Thunderbird to do various operations like Archive, Next, etc.

What I now realize is this happens because if I move the mouse over the Quick Move dropdown menu of previous folders it takes focus away from the field where I search for a folder. I am hoping there is some way this can be prevented.

**Comment by kewisch** [comment]
This will be fixed in 2.8.0, some keys were leaked through to the main window. Thanks for reporting!
