### ISSUE TITLE
Context menu slow to display after TB updated to 115

### ISSUE THREAD

**Issue by expdis** [kewisch/quickmove-extension#134]
Hi,

Just updated TB (Linux) to 115, notice Quick Folder Move's context menu is slow to display now.  It takes about 1 to 2 sec to display, before update it was instantaneous. 

Anyone else have this issue?

**Comment by kewisch** [comment]
Unfortunately I don't think there is much I can do to improve performance here, though I am open to ideas. I'm using the new extensions API, and otherwise roughly the same approach to load the folders. 1-2 seconds seems a lot, I guess you have a lot of folders?
