### ISSUE TITLE
Where are my keyboard shortcuts?!

### ISSUE THREAD

**Issue by arkanovicz** [kewisch/quickmove-extension#135]
First of all, thanks for your work.

But I discovered with horror that the control-M shortcut wasn't working anymore in the new version, that I had to click a button...

This is terrible for my workflow. I did my mails filtering only with the keyboard and now I have to alternate between the mouse and the keyboard at every mail...

Is there any way to bind some key to the action to open the menu and give the focus to the text field?

Thanks.

**Comment by rmmbr** [comment]
@arkanovicz: For using of your prefered shortcuts on your own system see https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox. Alternatively, you can define/set the legacy shortcuts in the settings of QFM 2.7.0.

**Comment by kewisch** [comment]
It should still work the keyboard as long as you use the new shortcuts. I have some updates in version 2.8.0 pending that might fix the remaining issues.
