### ISSUE TITLE
History doesn't show up anymore in the quick move popup

### ISSUE THREAD

**Issue by neliorc** [kewisch/quickmove-extension#137]
Since updating to 2.7.0, I no longer see the history of folders in the quick move popup. It always resets to my inboxes.

**Comment by kewisch** [comment]
Do you get any error console messages?

**Comment by kewisch** [comment]
I'm assuming you picked specific folders and that it is fixed with 947a593f70ea3454c0d1a788cc59c9e7500decfe which will be part of 2.8.1. Please create a new issue if that isn't the case and you've tested the updated version. It will be reviewed and deployed shortly.

**Comment by neliorc** [comment]
I will test it and let you know if the problem persists.

In the meanwhile, this is what I get in the console:

```
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
[popup.js:137](moz-extension://2ea0a8ea-4dd9-4714-a38d-65bc8c4c1932/popup/popup.js)
    unload moz-extension://2ea0a8ea-4dd9-4714-a38d-65bc8c4c1932/popup/popup.js:137
```

**Comment by kewisch** [comment]
That message is expected, it is because the popup has closed before the message I send to the background script completes processing, so it doesn't know where to send it. I don't actually need the result though, I just can't silence the message.
