### ISSUE TITLE
History and function not working in Conversation View

### ISSUE THREAD

**Issue by Morphine4u81** [kewisch/quickmove-extension#139]
Super new to Github and suggesting issues (as in this is my first) but I'm a huge fan of this extension for Thunderbird.

Anyway, when I'm in conversation view, the window/box will pop up, but I cannot search, there is no history, and it basically doesn't work. You may be aware already, but I wanted to share in case it helps!  I've attached a screenshot.
![QuickMove_ConvoView](https://github.com/kewisch/quickmove-extension/assets/153113034/8b25735e-481d-46af-b5da-d73dd93f75d8)

**Comment by kewisch** [comment]
You did well with github, thanks for checking in! That looks like an error occurred. Can you check Thunderbird's error console and let me know what it says?

**Comment by Morphine4u81** [comment]
No problem.  Again, I'm not very technical so I just opened the console up and grabbed a screenshot.  I hope this helps.
![ErrorIssue](https://github.com/kewisch/quickmove-extension/assets/153113034/ec42fb5f-da22-481a-83cc-3cbd2bd1e9a2)

**Comment by kewisch** [comment]
Hmm unfortunately I don't have a good answer based on those messages. To confirm, these are the messages you get when you simply open the popup? The Conduits message is "normal", at this point the popup is probably closed again and the response in the code just didn't make its way back, however I don't need that response.

The dead object could be related, but seems to be more around switching tabs. The warnings seem related to displaying email, and the DevToolsFrame also seems unrelated.

What happens if you begin typing in the textbox in the popup?

**Comment by Morphine4u81** [comment]
Nothing happens when typing into either of the text boxes.   This is true in conversation view, but if I'm in the regular inbox typing has the behavior I would normally expect.

**Comment by Morphine4u81** [comment]
Anything I can do to help better identify this?  I've noticed the same problem on my work laptop and home PC.  Different accounts, not that it would matter.

**Comment by kewisch** [comment]
To clarify, I was wondering if there are any specific messages that appear in the error console when you type something. Or if there are any other messages that something was not loaded. Unfortunately I don't have a good idea on what information you could provide that would help me reproduce this.

Maybe you could try some of the more generic tips, i.e. try uninstalling and re-installing the add-on, try disabling all other add-ons to see if that influences it, try again on a new Thunderbird profile to see if that makes a difference.

**Comment by Morphine4u81** [comment]
Understood. 
Okay, here's what I know.

- The other extensions I have- GCalTab, Google Chat Tab, PrintingTools NG, Provider for Google Calendar, and Send Later, when turned off... have not affected this problem. 
- It is a problem on two different PCs, both looking at different email accounts.
- When looking at the primary inbox or individual folders (directly), the function works as expected.
- The problem specifically seems to be when looking at emails in a conversation view (ctrl + shift + O).  When in Conversation View, both the shortcut (ctrl + shift + n) and the 'Quick Folder Move' button have the same error or lack of function. 
- I can say with certainty that this did work in prior versions (though I'm uncertain if it was an update to TB or this extension)
- Removing and then adding the extension did not have an effect.
- When I have the console open, I see no error or generated step/text when attempting to use this function other than what you have seen in my previous screen grab.

**Comment by Morphine4u81** [comment]
I'm not sure exactly what was updated last week, but as of this morning, things all seem to be working in Convo View.  So for the moment at least, thank you...seriously...thank you!

**Comment by kewisch** [comment]
Heh nice, things fixing themselves are the best! Let me know if it shows up again :-)
