### ISSUE TITLE
Specific Folders: good, but broken

### ISSUE THREAD

**Issue by georgmo** [kewisch/quickmove-extension#140]
Hi

I would like to use the Settings > specific folders option, as it would be very usefull to me.

When I try to set the specific folder, I can type and search and the dropdown lists the folders. But selecting any of them does not work. Its just the dropdown and no more actions are possible.

Thank you

**Comment by kewisch** [comment]
Hey, thanks for reporting. Do you get any error console messages?

**Comment by kewisch** [comment]
Aha, found it. Fixed in 947a593f70ea3454c0d1a788cc59c9e7500decfe
