### ISSUE TITLE
Make selected Go-to folder visible in folder tree

### ISSUE THREAD

**Issue by JohnFLand** [kewisch/quickmove-extension#143]
My recollection of past behavior of QM was that when going to a folder in a long list of folders, the selected folder became visible in the folder tree. That doesn't seem to be the case anymore, since many times a folder that I've selected is way down on the folder tree and not visible initially until I scroll down to it. Can the old way be re-stated?

**Comment by kewisch** [comment]
Unfortunately this isn't something I can control anymore. This would need to be a feature in Thunderbird's WebExtensions API, or done by default.

**Comment by kewisch** [comment]
I'm going to close this issue because there isn't really anything I can do here. If you want this to return file an issue in Thunderbird to make it so that when a folder is selected, it is scrolled into view and expanded in the sidebar. Thank you though for reporting!
