### ISSUE TITLE
Intermittent popup layout when set to 'Automatic'

### ISSUE THREAD

**Issue by unode** [kewisch/quickmove-extension#144]
The extension popup style is set to 'Automatic' after installation.
In my case, automatic means that 95% of the time I am presented with the wide layout. This is the layout I prefer.
In the other 5%, I see the compact popup instead.

Initially I thought that the compact option was a CSS glitch and some style failed to load.
This was reinforced by the fact that closing and reopening the pop-up typically switched to the wide layout.

As a user I always found this confusing and thought it was a bug until I saw that a setting existed to select between the two layouts.
However, I'm still curious about why "auto" is not consistently showing one or the other layout.

Is there an easy explanation and/or should this be considered a bug?

**Comment by kewisch** [comment]
If the window width is more than 1400px, it goes into wide mode. Are you getting that consistently?

**Comment by unode** [comment]
I haven't experienced it since I switched to "Always wide".

The only thing I can add is that I'm using a tiling desktop which could cause some window size adjustments.

I switched to "Automatic" and experimented a bit but wasn't able to replicate the behaviour. Might be an elusive one.

**Comment by kewisch** [comment]
I'm not really sure what this might be and I can't reproduce it. If you happen to come across this again and can find a consistent way to reproduce please let me know
