### ISSUE TITLE
Owl for Office365

### ISSUE THREAD

**Issue by infinitelyintrigued** [kewisch/quickmove-extension#145]
I use Owl for Office365 (https://www.beonex.com/owl/). I also have a Gmail account.
Quick Move can search through Gmail folders but not through my Outlook folders. (It only shows Inbox.) Quick Move is a great time-saver for my Gmail. That would be great, if it can work with Owl.
I believe Owl offers a one-month free trial period.

**Comment by afmoene** [comment]
Indeed, the popup of Quick Folder Move only shows the Inbox of your Outlook365/Owl account. But if you start entering the name of a folder in the search box, it will (at least for me) list the matching folders.

**Comment by infinitelyintrigued** [comment]
In my case, Quick Folder Move can find subfolders inside the Inbox as I type a name, but it cannot show any other folders outside of the Inbox.

**Comment by SaintDoormatius-cmyk** [comment]
I've having this exact issue, but only since the update for Thunderbird v.128.

**Comment by infinitelyintrigued** [comment]
Just an update. I'm using Thunderbird 128.3.1esr (64-bit) on Linux and QFM 2.9.2.
QFM can now find the Office365/Owl folders.
There's one folder and its subfolders QFM cannot find. I'm not sure why.
