### ISSUE TITLE
Sorting multiple messages only works once (dialogue not showing)

### ISSUE THREAD

**Issue by MrCruesliPants** [kewisch/quickmove-extension#147]
Thank you for continuing to provide this essential(!) feature through your add-on.

### What happened
I have just launched Thunderbird. I have multiple emails selected, and press the shortcut (Ctrl + H in my case). The sorting dialogue shows up and I can move my messages without problems. After this, selecting a single email and sorting via shortcut also works correctly. However, if I now try to select any other multiple messages, the sorting dialogue no longer shows up when I press the shortcut.

### Expected behaviour
Moving multiple messages works more than once

### Actual behaviour
Moving multiple messages only works once. After this, I have to restart Thunderbird in order to be able to sort multiple messages again.

---

### Settings

Thunderbird 115.9.0 (64-bit)
Quickmove 2.8.1

<p align="center">
  <img src="https://github.com/kewisch/quickmove-extension/assets/16578306/bb9f899c-1c88-49ca-8973-e6bb0a10a588" width="45%">
&nbsp; &nbsp; &nbsp; &nbsp;
  <img  src="https://github.com/kewisch/quickmove-extension/assets/16578306/f8a08465-25ff-4673-a408-7f84c36f14da" width="45%">
</p>

Is anybody else able to reproduce this?

**Comment by MrCruesliPants** [comment]
Error Console says
![error](https://github.com/kewisch/quickmove-extension/assets/16578306/a938bd1c-39a3-4a1d-8592-5684d02f0e22)

**Comment by kewisch** [comment]
Can you try again in 2.9.2+ ? I believe there are some related issues I fixed that might affect this.

**Comment by MrCruesliPants** [comment]
Hi @kewisch, thanks for the reply. I was actually able to fix this on my end. After adding the Quick Move button to the menu bar, the error no longer occurs. I will close this issue.

Thanks again for your support and maintenance of this essential tool!
