### ISSUE TITLE
Command String for custom shortcuts using tbkeys-lite

### ISSUE THREAD

**Issue by CPrescher** [kewisch/quickmove-extension#151]
Hi,

I would like to have a simpler shortcut when selecting mails than ctrl+shift+m - something like v. For this one can typically use something like tbkeys-lite - which allows to customize the shortcuts:

Example config there is: 

{
    "j": "cmd:cmd_nextMsg",
    "k": "cmd:cmd_previousMsg",
    "o": "cmd:cmd_openMessage",
    "f": "cmd:cmd_forward",
    "#": "cmd:cmd_delete",
    "r": "cmd:cmd_reply",
    "a": "cmd:cmd_replyall",
    "x": "cmd:cmd_archive",
    "c": "func:MsgNewMessage",
    "u": "tbkeys:closeMessageAndRefresh"
}

Is it possible to assign a "Quick Folder Move" command here? I tried to find in the source code, if there is something registered, but was not able to find it.

Thank you!

**Comment by ajgon** [comment]
I believe it's not possible in `tbkeys-lite`, since it doesn't allow for javascript evaluation. In `tbkeys`, you can do:
```json
{
        "m": "window.document.querySelector('[extension=\"quickmove@mozilla.kewis.ch\"]').click()"
}
```
