### ISSUE TITLE
Question/Issue Selecting a Folder Using the Keyboard

### ISSUE THREAD

**Issue by infinitelyintrigued** [kewisch/quickmove-extension#152]
I'm using Quick Folder Move 2.8.1 with Thunderbird 115.10.1.

I can open the Quick Folder Move dialog box to list folders but cannot use the keyboard to select a folder (e.g., using the up and down arrow keys). I disabled all the other extensions, but this issue persists. I can still select a folder using the mouse, but the keyboard is more convenient. How can I troubleshoot this issue?

Thank you,

**Comment by kewisch** [comment]
Can you try again with version 2.9.2 and Thunderbird 128?

**Comment by infinitelyintrigued** [comment]
Hi, I just tried 2.9.2 and noticed something. First of all, I had [Issue 150](https://github.com/kewisch/quickmove-extension/issues/150) also, but this issue seems to be fixed.
When I press the up/down arrow keys, no folder is highlighted as if QFM is not responding to those keys. However, when I press the Enter key, the selected message moves. The problem is I don't know to which folder it was moved.
I disabled all the extensions except QFM and reverted to the default theme. The same problem happens.

**Comment by kewisch** [comment]
When you press enter, it moves to the first folder in the list. I can't reproduce the arrow keys not working, are you on Linux by chance? I've heard a few Linux-specific issues which I believe might be in Thunderbird.

**Comment by infinitelyintrigued** [comment]
Yes, I'm using 128.2.0esr (64-bit) on Pop!_OS 22.04 LTS. 

Here are the messages found in the Thunderbird error console when I opened the Quick Folder Move dialog box, chose Go To, and then pressed the down arrow twice to select Important (which I couldn't see), and pressed Enter. I don't know if they help or not.

```
Content-Security-Policy warnings 3
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
popup.js:162
selected => background.js:9:13
browser is null ext-tabs.js:76:1
```

**Comment by infinitelyintrigued** [comment]
Just an update. I recently switched from the Snap version of Thunderbird to the version downloaded from thunderbird.net directly. QFM works as expected. I can now use the keyboard to select a folder.

However, I still have one question. I'll make a separate post.

**Comment by kewisch** [comment]
Thanks for the feedback. Strange that it doesn't work in the Snap version, there shouldn't be a difference for this type of thing. Glad it works though!
