### ISSUE TITLE
Do you plan to make it compatible with Thunderbird Beta 127 

### ISSUE THREAD

**Issue by CharlesDelorme** [kewisch/quickmove-extension#153]
Simple question, I guess not a simple answer  ;-)

I don't know yet when version 127 will be release or if there are issues porting this extension to this version. (or only mark it compatible)

When searching for extension within Thunderbird, it found version 1.9 which can be install but do not work (only tested the shortcut and didn't test further). It refused to install 2.8.1.

Thanks

**Comment by CharlesDelorme** [comment]
I tried to simply modify the manifest.json to allow version up to 130. The plugins installs correctly but it seems it cannot access the folder tree despite the right which are good.

**Comment by kewisch** [comment]
Some changes were necessary, see #156 now :)
