### ISSUE TITLE
Thunderbird 128 compatible version ready in the next few days

### ISSUE THREAD

**Issue by siffegh** [kewisch/quickmove-extension#156]
Please update for TB v.128.

**Comment by TmtStss** [comment]
@kewisch. Is there any plan to update this amazing extension to remain compatible with future TB versions ?

**Comment by kewisch** [comment]
Thanks for the reminder, I kind of assumed it would just work. I've submitted a new version that fixes the issues for review on ATN, it should be approved in the next few days.

**Comment by kewisch** [comment]
And it is approved!

**Comment by siffegh** [comment]
Thank you!

**Comment by CharlesDelorme** [comment]
So I'm now ready to upgrade to 128 :-) Thks !
