### ISSUE TITLE
Can't move messages on Thunderbird 128

### ISSUE THREAD

**Issue by ricalexm** [kewisch/quickmove-extension#161]
Hi!

I've installed the updated version for Thunderbird 128 but can't seem to be able to move any messages using it.

Steps that trigger the error:w
When I trigger the extension, and select the folder to be moved, the icon of the extension just keeps spinning, and the following error message is displayed in the error console:
“Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved”
on the file:
[popup.js:162](moz-extension://0d8241f2-664f-42c3-8f0b-8e0bd8c8dd80/popup/popup.js)

Can somebody help with this?

Thank you!

**Comment by wondering639** [comment]
Had the same issue like you. After restarting Thunderbird it sometimes works - while still giving this error message.

**Comment by kewisch** [comment]
Solved in QFM 2.9.2 which is pending review
