### ISSUE TITLE
Feature request : do not reset folder selection when changing action with the keyboard

### ISSUE THREAD

**Issue by CharlesDelorme** [kewisch/quickmove-extension#162]
First of all : absolutely not urgent ! Troubleshooting TB 128 will help many more people :-)

Context : I only use Quickmove with my keyboard. When I open it, I search the folder, use the arrow down key to highlight the correct folder then sometimes use the arrow right key to change the action from move to goto. This action resets folder selection which must be done again

Workaround : basic workaround is to select the action before selecting the folder, which is what the UI suggests since actions are on the top, and it is not *that* painful

Desired solution : if possible, do not change the folder selection if the action is modified.

Thanks a lot

**Comment by kewisch** [comment]
Makes sense, this would be a nice addition!

**Comment by CharlesDelorme** [comment]
2.9.2 seems to be implementing this. 

I migrated my TB to 128 in production this morning, I reinstall the extension which didn't enjoy the upgrade (which might be caused by my company packaging) and I don't know which previous version I had :-/

Anyway, thank you !

**Comment by kewisch** [comment]
I fixed this more intentionally in c134d364c581e01ecec84b176101d3a1cb768826 which will be part of 3.0.0


[quick_folder_move-3.0.0pre.zip](https://github.com/user-attachments/files/17964764/quick_folder_move-3.0.0pre.zip)
