### ISSUE TITLE
Moving multiple messages with TB 128

### ISSUE THREAD

**Issue by borouhin** [kewisch/quickmove-extension#164]
Steps to reproduce (extension 2.9.0, TB 128.0esr):
1. Select multiple messages
2. Try to move them to a folder using extension (via button or keyboard shortcut)
3. Nothing happens, messages are not moved
4. Then click any other message - it is moved to the folder you've chosen in step 2, not the messages you've selected initially

**Comment by Rockee79** [comment]
Hi there,

the same problem here... same Thunderbird version under Win 11  v 23H2 Build 22631.3958.
If i try to move multiple messages to a specific destination there is only a spinning cycle icon

![Spinning Cycle](https://github.com/user-attachments/assets/8ca4e72c-8bc1-4c44-9eec-40939df3151d)

**Comment by TmtStss** [comment]
Very similar to #163

**Comment by gypsychk** [comment]
@borouhin It's not a fix, but I found that pressing the right arrow moves one of the messages in the selected thread into the specified directory.

**Comment by kewisch** [comment]
I can reproduce this

**Comment by kewisch** [comment]
This should be resolved with qfm 2.9.2 which is in queue for release. Grab the xpi from the releases page if you can't wait :)

**Comment by borouhin** [comment]
I confirm everything works as expected in v. 2.9.2. Thanks!

**Comment by kewisch** [comment]
Thank you everyone for the quick responses and support in finding the issue. This made it a lot less painless to identify the issue and fix it. You are the best!
