### ISSUE TITLE
Ctrl + M sometimes shows contents of clipboard

### ISSUE THREAD

**Issue by mclaborn** [kewisch/quickmove-extension#17]
Thunderbird 68.2.2
Ubuntu 18.04
Quick Folder Move 1.7.0pre2

I can't reproduce this at will. It is not a new but, it was happening in versions before 1.7. 

Sometimes when I hit Ctrl + M to move a message, the contents of the clipboard shows up in the box where you can type the destination folder name. I get around it by clicking to another message then back to the original message.

**Comment by kewisch** [comment]
This is a "feature". If you select text, then it will pre-fill that in the move textbox. Useful if you want to move it to a folder of something mentioned in the message.

**Comment by mclaborn** [comment]
I'd like the option to be able to disable this.
