### ISSUE TITLE
[bug] cannot use arrows to move cursor in search box, only delete previously entered chars

### ISSUE THREAD

**Issue by liar666** [kewisch/quickmove-extension#170]
Hi,

Thanks for the great tool.

When I have ThB opened, and I click on the "Quick Move" logo at top right, there's a popup that appears, with "Move" action selected by default. That's nice.
The problem is when I type stuff in the search box here and I make mistakes, I cannot use the kb arrows to move cursor in search box to correct a mistake that would have occurred several chars ago. I can only delete all the char typed after this mistake, then correct mistake, then enter again the remaining chars.

**Comment by kewisch** [comment]
I thought we already had an issue on this, I noticed this as well. Unfortunately that will mean yet another keyboard change, I'd have to move the switching actions to something like shift+arrow key, which won't be very apparent, so I'd need some sort of onboarding ideally in context.

**Comment by CharlesDelorme** [comment]
I must admit I always hit backspace to remove all the wrongly spelled characters and I had never tried using the arrow keys to go "inside" the search and correct. I won't have any correct idea. Changing the "action" from arrow keys to ctrl-arrow or shift-arrow doesn't seems to be painful

**Comment by kewisch** [comment]
If someone could test the pull request on Linux or Windows I'd appreciate!

**Comment by kewisch** [comment]
Here is a build for the pull request. @CharlesDelorme  @liar666 can you give it a try? What OS are you on?
[quick_folder_move-2.9.3pre.zip](https://github.com/user-attachments/files/17449444/quick_folder_move-2.9.3pre.zip)

**Comment by CharlesDelorme** [comment]
Thank you for the zip (didn't know how to extract it from github :-(
I removed my previous plugin, renamed .zip in .xpi and installed this version.

ctrl-shift-N works to call the extension
the yellow box appears when trying to use the arrow keys
the left/right keys allow to move inside the searched word
up/down keys work

BUT
the ctrl-left/right doesn't move the cursor. It moves it word to word (if only one searched word it moves from the end to the beginning or the opposite)

This is not the expected behavior, sorry

OS : windows 10.0.19045.5011
Thunderbird : 128.3.1esr (64 bits)
French keyboard (and OS and TB)

I'm reverting to the previous (store) version of the plugin

If you provide a new zip I'll be able to test it faster and not wait one month…

**Comment by CharlesDelorme** [comment]
unfortunately, no, almost the same behavior (except the yellow warning box which doesn't appear everytime)

Maybe, instead of binding the action change key to "ctrl-arrow", it could be "tab" (and shift-tab) ? For the time being, tab key moves to the folder list, which is well done by arrow keys

**Comment by kewisch** [comment]
I can't use tab since that would mess with the focus order. Microsoft's Windows VMs are unfortuantely out of stock right now, so it will be difficult for me to debug/test. 

Can you see what happens when you press ctrl+arrow at https://w3c.github.io/uievents/tools/key-event-viewer.html ?

**Comment by kewisch** [comment]
[quick_folder_move-2.9.3pre3.zip](https://github.com/user-attachments/files/17798685/quick_folder_move-2.9.3pre3.zip)

Here is a random attempt to get it to work.

**Comment by CharlesDelorme** [comment]
Randomness seems good :-) Yes, I think it works as expected by @liar666 
* arrow keys move in the text and can correct it
* ctrl-arrow move the action

I'll keep this version (pre3) a while to get used to this new behavior and verify it really works. Nice job :-) (I'll miss the "move and goto" action now !)

**Comment by CharlesDelorme** [comment]
Fun fact, when a folder is selected, left/right arrows move the action. For me it is not a problem.

**Comment by kewisch** [comment]
For me it is worse, when a folder is selected left/right moves the action and also focuses the textbox. Likely was that way before, but worth fixing. How is this?

[quick_folder_move-2.9.3pre4.zip](https://github.com/user-attachments/files/17813136/quick_folder_move-2.9.3pre4.zip)

**Comment by CharlesDelorme** [comment]
I get your point, and pre4 works correctly (didn't find any problem with pre3 so I keep this pre4 to check)

**Comment by kewisch** [comment]
Super. I'm going to go ahead and merge the PR. Feel free to keep pre4 installed, if you encounter any issues you can file a new bug. I'll get this out for everyone soon.

**Comment by kewisch** [comment]
Thank you so much for your testing and quick feedback!

**Comment by CharlesDelorme** [comment]
Just to let you known everything is ok and I got used to ctrl-arrow really quickly, definitively a go 👍
