### ISSUE TITLE
`Ctrl+Shift+N` open `Quick Compose` tab instead of expected popup

### ISSUE THREAD

**Issue by iago-pssjd** [kewisch/quickmove-extension#172]
Hi!

I have just installed this extension. When I try the shortcut Ctrl+Shift+N, a new tab in thunderbird opens with the title `Quick Compose` and the next aspect:
![image](https://github.com/user-attachments/assets/e17cd16a-9524-4da6-a47d-501051290b9f)
I get the same behaviour after changing the shortcut.

Thanks
Debian 12 + Thunderbird 115.15.0 + Quick Folder Move 2.9.2

**Comment by kewisch** [comment]
Do you have the link to this add-on? I'm using the standard mechanism to set extension shortcuts, you should be able to change them for each of the add-ons in the add-ons manager when you click on the cog icon.

**Comment by iago-pssjd** [comment]
@kewisch 

I have tested again. Both shortcuts I tried were used by other extensions. With a different one, it worked. Thanks!

**Comment by iago-pssjd** [comment]
By the way, the addon which has the same  default shortcut is Thunderbird conversations

**Comment by kewisch** [comment]
Thanks for checking!
