### ISSUE TITLE
Quick Move just stoppped to autofill location field, after only one time

### ISSUE THREAD

**Issue by jefcool** [kewisch/quickmove-extension#173]
As your extension is of great interest, years ago it worked perfectly, but this version expereiences lots of issues, as I can't use it anymore, because, after one successfull try, it has worked correctly only 3 or 4 times, but now, autofill path stays blank with no focus.
I guess it's not a big issue, but lead to a permanent failure.

Thank you for your help, I hope to have good reason to participate once cured.

Cheers

**Comment by kewisch** [comment]
Is the whole dialog blank, or just a part of it? Can you provide a screenshot? See also #158 which has a fix if you are on Linux/Wayland.

**Comment by kewisch** [comment]
It looks like I haven't heard back on this issue, therefore I am closing this issue. If this problem persists in the latest version of Thunderbird and the Quick Folder Move extension, please re-open this issue.
