### ISSUE TITLE
Quickmove doesn't work at all with Thunderbird 128.2.3esr or newer

### ISSUE THREAD

**Issue by sirio81** [kewisch/quickmove-extension#175]
Hi, I'm running Kde Neon (ubuntu 22.04).
Quickmove extension stopped working after the upgrade of Thunderbird to 128.2.3esr.
I also tried to run a beta version 131.0b6 (64bit) and the plugin doesn't start anyway.
It just opens a blank window:

![image](https://github.com/user-attachments/assets/c37a78ba-b628-40dc-b8f3-40e46284859b)

This is a great tool that I wish it would be the integrated in the main project (it work way better then the default way of moving messages).

Thank you very much for your job.

**Comment by olaulau** [comment]
maybe related to wayland, I have the same white popin on my laptop (wayland), but works well on my desktop (X11).
 same OS (debian desting), same thunderbird and plugin versions.

**Comment by sirio81** [comment]
I tried to change this setting and restart
![image](https://github.com/user-attachments/assets/1ca0c260-031b-4454-81f4-110c5939a486)

but is still doesn't work.

**Comment by olaulau** [comment]
any update ?

**Comment by f-fr** [comment]
Not sure if it is Quickmove's fault. Other extensions have the same problem (AutoArchive for instance). My current workaround is to force thunderbird to start in X11-mode:

```
env WAYLAND_DISPLAY="" thunderbird
```
Not perfect, but works for now.

**Comment by olaulau** [comment]
> Not sure if it is Quickmove's fault. Other extensions have the same problem (AutoArchive for instance). My current workaround is to force thunderbird to start in X11-mode:
> 
> ```
> env WAYLAND_DISPLAY="" thunderbird
> ```
> 
> Not perfect, but works for now.

so you are confirming my assumptions : it's fully related to wayland.

**Comment by axelsimon** [comment]
Duplicate on #158.
Can we close this one and concentrate efforts on #158?

**Comment by olaulau** [comment]
yes, #158 seems more active with upcoming solutions.
