### ISSUE TITLE
Extension font size does not adapt to Thunderbird font size

### ISSUE THREAD

**Issue by graelo** [kewisch/quickmove-extension#177]
Hi, thanks for this useful extension.

I'm new to Thunderbird. I'd like to change the font size in the popup this extension displays. Currently, the font sizes are much bigger than the rest of my TB interface. The extension is functional though.

I tried tweaking the `popup.css`: reduce the font size for `folder-list` and `tags-list`, (then recompile and add again), but I was surprised this has no effect. Maybe this behavior is normal in TB? I think I saw some settings being read from browser local storage, could it interfere with what I'm trying to do?

Thanks!

**Comment by kewisch** [comment]
If you add `font-size: 11px` to this rule, it should work. https://github.com/kewisch/quickmove-extension/blob/e5490f3ae4bb806c1cd016335b1e35743c2a97b6/src/popup/popup.css#L32-L40

I'm not changing the font size aside from relative changes in the quickmove, so the base font size seems to be "normal" for the extension popup. Getting the base font size from the main window could be quite a hack, I'll have to see if the base font size can be adjusted in Thunderbird for the popup, but I suspect this won't happen for the current ESR.

**Comment by kewisch** [comment]
Filed this issue:

https://bugzilla.mozilla.org/show_bug.cgi?id=1925836

**Comment by graelo** [comment]
Thanks @kewisch! It works perfectly.

If I manage to get it work, I'll open a PR to expose this setting in the UI.

Cheers and thanks again for this extension

**Comment by kewisch** [comment]
I'd rather not make this a setting, there should be a sensible default for this.

What we should likely do until the upstream bug is fixed, figure out the default font sizes on for Thunderbird per platform, hook into the code that sets Thunderbird's font sizes, then use the result to determine the extension font size:

comm-central on searchfox.org is the right place to start looking, along with Thunderbird developer tools.

**Comment by kewisch** [comment]
I fixed this within the extension temporarily, the fix should not interfere with whatever comes from Thunderbird eventually.

0465d3bc98c65666b258ade054c3324d010b4da3
