### ISSUE TITLE
QFM Cannot Find One Folder

### ISSUE THREAD

**Issue by infinitelyintrigued** [kewisch/quickmove-extension#179]
I'm using 128.3.2esr (64-bit) on a Pop!_OS (Linux) PC. I have an Office 365 mail account.

I have a folder structure that looks something like this:
```
Archive
  2020
    H1
    H2
  2021
    H1
    H2
...
  2024
    H1
    H2
  2025
    H1
    H2
```
QFM can find all H1 and H2 folders except 2024 H1. I'm not sure why.
Does QFM use some sort of indexing? (I suspect some type of index corruption.) If it does, how do I rebuild it?

Thank you,

**Comment by kewisch** [comment]
Are you using the Owl extension in addition, or just a regular imap account? I don't do anything special with the folders, I simply retrieve them from Thunderbird's folder API

**Comment by infinitelyintrigued** [comment]
I'm using IMAP.

**Comment by kewisch** [comment]
Can you try the "repair folder" option on the parent folder? I'm using the standard folder API from Thunderbird. If repair folder doesn't work, you could try pasting this into devtools and see if the folder shows up there:

```javascript
function processFolders(folder) {
  return [folder.id].concat(folder.subFolders.map(processFolders).flat());
}
await browser.accounts.list().then(accts => accts.map(a => a.folders.map(processFolders).flat()));

```

Go to Tools > Developer Tools > Debug Add-ons > Quick Folder Move > Inspect . If you don't see a console in the bottom bar, press Escape. Paste the code, press Run. Expand the `Array` on the right, which will be one per account. Expand the right array again and look through the folders.

**Comment by infinitelyintrigued** [comment]
I fixed it - sort of.
The "repair folder" did not work.
So, I unsubscribed from the 2024 H1 folder and renamed it to "2024 H1 (old)" in Outlook.
When I resubscribed to the "2024 H1 (old)" folder, QFM was able to find this folder and its subfolders. Strange.

Anyway, it's working now. Thanks. I really like QFM.

**Comment by infinitelyintrigued** [comment]
I think I finally understand what's causing this issue.
It appears that when a folder is set to be an archive folder (Edit > Account Settings > Copies and Folders > Message Archives), that folder and its subfolders are not searched by QFM. (I originally had the 2024 H1 folder to be the archive folder, which was probably why QFM did not show.)

I just moved the 2021 H1 folder out of the Archives folder and set the Archives folder to be the archive folder. Now, QFM only finds the 2021 H1 folder and its subfolders. The other 20XX folders and their subfolders are not shown.

**Comment by kewisch** [comment]
Ah good detective skills. Indeed, archive folders are not searched by default. Glad you found a solution!
