### ISSUE TITLE
Indent Folder Names under each account

### ISSUE THREAD

**Issue by brackenhill-mob** [kewisch/quickmove-extension#18]
Please can you indent the folder names under each account?

I have about 12 accounts with multiple folders in each account with the same name (ie "Sales & Marketing" x12)

It would make it much easier to spot the account I need ;)

TIA

**Comment by kewisch** [comment]
So you mean just indent all folders by lets say 10px and keep the heading at its current position? That should be simple to do :)

**Comment by brackenhill-mob** [comment]
Yes that's exactly what I mean ;)
--

**Comment by bderubinat** [comment]
Hello,

As a related topic, I have similar named Folders in the same account.
I'd rather always have the folder Full name.

The improvement probably lies in there where it would be possible to always the label as the FullName (or if a given option is set) 

```
if (lowerLabel in fullPathMap) {
    label = Quickmove.getFullName(folder);
}
```
Thanks for the good add-on.

**Comment by MLopez-Ibanez** [comment]
> Workaround in fork: https://github.com/bderubinat/quickmove-extension

@bderubinat , please open a pull request. @kewisch recently merged a bunch of them.

**Comment by kewisch** [comment]
The new version highlights the accounts with a special heading, this should make it easier to see same names in different accounts. Hope this helps!
