### ISSUE TITLE
Uncaught Exception - Folders not listed

### ISSUE THREAD

**Issue by jkbrinso** [kewisch/quickmove-extension#180]
When attempting to use QuickMove the following message appears in the debug console:

Uncaught (in promise) TypeError: folder is undefined
    getSortKey moz-extension://cf9e7303-e924-4851-9bc1-6aa39312ba0f/common/foldernode.js:81
    sorter moz-extension://cf9e7303-e924-4851-9bc1-6aa39312ba0f/common/foldernode.js:101
    walk moz-extension://cf9e7303-e924-4851-9bc1-6aa39312ba0f/common/foldernode.js:35
    walk moz-extension://cf9e7303-e924-4851-9bc1-6aa39312ba0f/common/foldernode.js:39
    folders moz-extension://cf9e7303-e924-4851-9bc1-6aa39312ba0f/popup/popup.js:90
    load moz-extension://cf9e7303-e924-4851-9bc1-6aa39312ba0f/popup/popup.js:90
    async* moz-extension://cf9e7303-e924-4851-9bc1-6aa39312ba0f/popup/popup.js:194
foldernode.js:81:5

It had been working OK, but the problem appeared within the last few weeks. I am able to pull up the Quick Move dialog with the shortcut key or clicking the Quick Move button. The dialog has buttons for Move, Copy, Goto, and Tag, followed by two blank text fields that I can type in but which do not do anything noticeable. 

The problem occurs regardless of whether, in the settings, I choose "Recent Folders", "All folder", or "Specific Folders." The error also appears in the console when I am on the settings window, and the space under the Recent, All, and Specific folders options is blank. 

I am using:
- Windows 10 Pro
- Thunderbird version 128.3.2esr 64-bit (the latest version)
- the Owl extension to access Exchange folders (but the problem occurs even when I have a local folder selected)

There was an issue with Owl and Exchange Folders and Quick Move a while back, but that issue was resolved and things were working fine. 

Thanks!

**Comment by jkbrinso** [comment]
Update: I can confirm that when Owl is disabled, Quick Move works again. So it obviously has something to do with the Exchange folders.

**Comment by kewisch** [comment]
Not the first owl-related issue I've seen, unfortuantely. I'm not sure when I'll get to this since I don't have an owl to reproduce, but it might be easy to figure out without. Can you confirm you are using quick folder move 2.9.2 ?

**Comment by rigow** [comment]
TB 128.3.3esr with QM 2.9.2 it cannot find certain folders. On opening Quick Move displays certain folders, but not others. The quick move selection dialog shows 20 of over a hundred folders. When filtering (dynamic by typing the first letters) the desired folder does not appear. I have no error message in the TB error console.

**Comment by kewisch** [comment]
@rigow are you getting the same exception as here? Otherwise this might be a different issue. Though please check if the folders you are searching for are marked archive folders or some other set of folders excluded.

@jkbrinso Do you maybe have a way to get me test access to an exchange server? I don't have one so it is hard to figure out what to do.

Here is a version that has some more logging. It doesn't try to work around the error yet, because those items being null should not happen and I'd rather find the root cause.

Look out for log messages with "NULL FOLDER ENCOUNTERED" which should appear near the exception.
Also look out for "ADD NODE" or "SET ACCOUNT ITEM" where it says `null` at the end.

[quick_folder_move-2.9.3pre.zip](https://github.com/user-attachments/files/17789659/quick_folder_move-2.9.3pre.zip)

**Comment by jkbrinso** [comment]
@kewisch Thanks so much for spending some time on this. 

I cannot give you test access. 

I installed the pre-release version provided and looked at the console. Here is what I see:

- It appears to successfully "ADD NODE" for all the folders in the exchange account (it is a very long list)
- It then moves on to the Local Folders
- There are only three folders in my local folders, Trash, Outbox, and Temp
- It appears to successfully "ADD NODE" for all three of those
- The next entry is "NULL FOLDER ENCOUNTERED"

Note: I do not have any other accounts or folders that I am aware of that are not successfully processed. It looks like it is successfully ADD NODEing all the folders I actually have. 

Here is a dump of the last few entries in the console:

SET ACCOUNT ITEM 
Object { id: "account2", name: "Local Folders", type: "none", rootFolder: {…}, identities: [], folders: (3) […] }
[foldernode.js:167:13](moz-extension://3a493275-ef89-4c14-972a-e9b1cbb00de1/common/foldernode.js)

ADD NODE /Trash  ->  
Object { id: "account2://Trash", name: "Trash", path: "/Trash", specialUse: (1) […], isFavorite: false, isRoot: false, isTag: false, isUnified: false, isVirtual: false, accountId: "account2", … }
[foldernode.js:119:13](moz-extension://3a493275-ef89-4c14-972a-e9b1cbb00de1/common/foldernode.js)

ADD NODE /Unsent Messages  ->  
Object { id: "account2://Unsent Messages", name: "Outbox", path: "/Unsent Messages", specialUse: (1) […], isFavorite: false, isRoot: false, isTag: false, isUnified: false, isVirtual: false, accountId: "account2", … }
[foldernode.js:119:13](moz-extension://3a493275-ef89-4c14-972a-e9b1cbb00de1/common/foldernode.js)

ADD NODE /Temp  ->  
Object { id: "account2://Temp", name: "Temp", path: "/Temp", specialUse: [], isFavorite: false, isRoot: false, isTag: false, isUnified: false, isVirtual: false, accountId: "account2", … }
[foldernode.js:119:13](moz-extension://3a493275-ef89-4c14-972a-e9b1cbb00de1/common/foldernode.js)

NULL FOLDER ENCOUNTERED 
Object { parent: {…}, skipArchive: true, _children: {…} }
Object { parent: {…}, skipArchive: true, _children: {…}, item: {…} }
[foldernode.js:106:15](moz-extension://3a493275-ef89-4c14-972a-e9b1cbb00de1/common/foldernode.js)

Uncaught (in promise) TypeError: folder is undefined
    getSortKey moz-extension://3a493275-ef89-4c14-972a-e9b1cbb00de1/common/foldernode.js:82
    sorter moz-extension://3a493275-ef89-4c14-972a-e9b1cbb00de1/common/foldernode.js:109
    walk moz-extension://3a493275-ef89-4c14-972a-e9b1cbb00de1/common/foldernode.js:35
    walk moz-extension://3a493275-ef89-4c14-972a-e9b1cbb00de1/common/foldernode.js:39
    folders moz-extension://3a493275-ef89-4c14-972a-e9b1cbb00de1/popup/popup.js:93
    load moz-extension://3a493275-ef89-4c14-972a-e9b1cbb00de1/popup/popup.js:93
    async* moz-extension://3a493275-ef89-4c14-972a-e9b1cbb00de1/popup/popup.js:197
[foldernode.js:82:5](moz-extension://3a493275-ef89-4c14-972a-e9b1cbb00de1/common/foldernode.js)

Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
[popup.js:165](moz-extension://3a493275-ef89-4c14-972a-e9b1cbb00de1/popup/popup.js)
    unload moz-extension://3a493275-ef89-4c14-972a-e9b1cbb00de1/popup/popup.js:165

**Comment by kewisch** [comment]
> NULL FOLDER ENCOUNTERED
> Object { parent: {…}, skipArchive: true, _children: {…} }
> Object { parent: {…}, skipArchive: true, _children: {…}, item: {…} }
> foldernode.js:106:15

If in the second Object row you expand the `item`, which folder is that? And if the Object in the first folder has _children, can you infer which folder that should be? Normally that first row should also have an `item` property, so trying to see why it didn't get one.

Also can you go through the whole ADD NODE list and see if there is one with a `null` at the end? I really don't see a code path where `item` is not set, but it seems there must be one.

**Comment by jkbrinso** [comment]
Maybe this is the result of me being clueless, "item:{...}" does not expand. It looks like it would, but clicking on it does nothing. Right-clicking on it brings up context menu choices, none of which are expand or any variation thereof. I can "copy all messages" and paste them into a text editor, but when I do that, it's still just curly braces and dots. 

I went through the ADD NODE list and I could not find one with "null" at the end. I also did a text search for null on the entire body of messages, and the only time the word "null" appears is in the message "NULL FOLDER ENCOUNTERED" referenced above in this thread. Here are some typical entries, and basically they all look like this:

ADD NODE /Inbox  ->  
Object { id: "account4://Inbox", name: "Inbox", path: "/Inbox", specialUse: (2) […], isFavorite: false, isRoot: false, isTag: false, isUnified: false, isVirtual: false, accountId: "account4", … }

ADD NODE /Inbox/Todo  ->  
Object { id: "account4://Inbox/Todo", name: "Todo", path: "/Inbox/Todo", specialUse: [], isFavorite: false, isRoot: false, isTag: false, isUnified: false, isVirtual: false, accountId: "account4", … }

The "..." at the end appears as an underscore in the browser toolbox "_", not as "...", but that could be my 45 year old eyes starting to go. 

I also looked through all the ADD NODE entries to see if anything looked amiss, and the only thing that appears even slightly amiss (but not unexpected) is that the id of longer folder names is truncated with a code. 

Thanks again for your efforts to resolve this.

**Comment by kewisch** [comment]
No, the expansion thing is likely a bug in Thunderbird, or simply because the console can't access that context any more once the popup closes. I might need to expand the logging a bit, will get back to you.

**Comment by kewisch** [comment]
[quick_folder_move-2.9.3pre.zip](https://github.com/user-attachments/files/17882624/quick_folder_move-2.9.3pre.zip)

Moar debugging. It should now tell you the parent item with the path as well as some info about the children so you can identify the folder that is failing. Let me know which folder this is (I don't care about the name unless it has uncommon characters, but type and other things might be useful). If you are planning to fix it by potentially deleting an unneeded folder please hold up, I'd like to verify a fix before we lose the reproducible situation :)

**Comment by jkbrinso** [comment]
OK... PROGRESS!!!!! I know the reason for the error and I can re-produce it. It does appear to be either an Owl or a Thunderbird bug, but perhaps you can work around it. The new error message revealed the parent folder of the folder with the issues. This narrowed it down enough to figure out. 

The error occurs when a folder in Exchange has a / in the name. In this case, Owl does not process the folder properly and it does not appear on the folder list in Thunderbird at all -- it's as if it does not exist. But, for reasons maybe you can determine, Quick Move still "sees" the folder as a null and chokes trying to process it. I suppose what's happening under the hood is that Owl chokes on the /, spits out a null folder as a result, and then that null folder gets ignored when thunderbird shows me my list of folders, but it still exists behind the scenes for other plugins to crash and burn on. 

I know you said not to, but I renamed it, and Quick Move works. I created a new folder name with a / in it (using Outlook) and Quick Move stops working again. 

I hope this enables you to work around it. I'm happy to test any solutions you want to throw at me.

**Comment by jkbrinso** [comment]
Another data point -- another extension that I have been using when Quick Move does not work, Move-msg, is able to see the errant folder, but only "sees" the part after the "/". For example, a folder named foo/bar will come up in Move-msg as if it is named "bar". Attempts to move a message to the folder fail.

**Comment by jkbrinso** [comment]
And, BTW, making sure that I do not have folders with a / in the name is a perfectly acceptable work-around for me if you don't want to devote any more time to this.

**Comment by kewisch** [comment]
Ahaha I knew this would bite me some day. I'm using a simple string split to get folder parts instead of an API call each time to aid performance. I'll see if I can do something here, but maybe you can file an owl bug and ask them to not use / in the folder path name? Please link the bug in case I need to reach out to the developers.

**Comment by jkbrinso** [comment]
Will do.

**Comment by kewisch** [comment]
[quick_folder_move-3.0.0pre.zip](https://github.com/user-attachments/files/17964764/quick_folder_move-3.0.0pre.zip)

Uh I went a bit overboard and rewrote portions of the backend :D This was also to support a different feature, but it should actually not fail with the / folder. Can you give it a spin?

**Comment by jkbrinso** [comment]
Hi! Thanks so much for this. I'm sorry it took so long to get back to you with the results of this test. I have big good news and a little bad news. 

GOOD NEWS
- The plugin essentially works again, at least for all the folders that do not have "/" on the name. 

BAD NEWS
- If there is an Exchange folder with a "/" in the name, QuickMove shows only what comes after the "/" -- so a folder named "Client/Project" appears as "Project"
- If I attempt to move an email into the "Project" folder, there is an Owl error in the log (not a quickmove error) and the email is not actually moved. 

My suggestions, if full support for these annoyingly-named folders from Exchange is not possible:
- Maybe do nothing. Good enough is good enough. I'd be totally happy if you marked this one as "solved" as-is. 
- Or maybe suppress display of folders with "/" in the name entirely in QuickMove. As I mentioned, they do not show up in Thunderbird's regular  interface at all, presumably because Owl can't deal with them correctly.
- If QuickMove detects one of these folders, some sort of user message or flag by the folder in the QuickMove interface indicating that folders with "/" in the name are not supported might be helpful.

**Comment by kewisch** [comment]
Alright, it was certainly worth a try. I'm going to go with option A, do nothing, and mark this completed. If they don't show up in the normal user interface, then I'd say this is more up to Owl to fix so they are not included or properly encoded. Thank you for testing, much appreciated!
