### ISSUE TITLE
Goto Tag View

### ISSUE THREAD

**Issue by nickwynja** [kewisch/quickmove-extension#182]
Thanks for this extension! I'd like to see Thunderbird Tags in the Goto menu so I can quickly navigate to a specific tag view. Basically the same options that currently show in the 'Tag' menu in QuickMove would also populate within the 'Goto' menu alongside folders so I could navigate to either.

**Comment by kewisch** [comment]
This was a bit more work to get done, can you give this one a try?

[quick_folder_move-3.0.0pre.zip](https://github.com/user-attachments/files/17964764/quick_folder_move-3.0.0pre.zip)

**Comment by kewisch** [comment]
Ah yes I came across this as well. I don't know if I am able to turn on the tags view, so I'll probably have to show an inline error or something like that.

**Comment by kewisch** [comment]
<img width="350" alt="image" src="https://github.com/user-attachments/assets/8d54a7aa-a055-4f8f-b9be-e69e6500f54f">
Going with something like this now. Thanks for testing!

**Comment by CharlesDelorme** [comment]
I discover this view :-) I didn't know about the Tag folder view. Translation added.
