### ISSUE TITLE
Does not see folders set to other under copies & folders

### ISSUE THREAD

**Issue by JeusuDigital** [kewisch/quickmove-extension#188]
In Thunderbird account settings when configuring an email account under Copies & Folders settings if Message Archives is set to the top radio option **"Archives" Folder on:** then the archive folders are visible in the addons search but if this is set to **Other:** then the folders do not appear in the search.

**Comment by kewisch** [comment]
This isn't something I can fix unfortunately. QFM will filter out folders that have the "Archive" flag. If Thunderbird does not set the archive flag on that "other" folder, then I have no way to detect this. You may be lucky filing a Thunderbird issue either to do so.

The upcoming 3.0 will have a way to exclude arbitrary folders, which should fix your use case.
