### ISSUE TITLE
Popup disappears when a new message appears in the message pane

### ISSUE THREAD

**Issue by billsacks** [kewisch/quickmove-extension#191]
First: Thank you for this fantastic extension!

This might be a Thunderbird issue rather than an issue with the extension....

I find that the Quick Move popup disappears when a new message appears in the message pane. This often happens due to the following sequence of events:

(1) Select a message in the message list

(2) Compose a reply to the message and send it

(3) Immediately invoke Quick Move on the original message, before the sent message has appeared in the thread in the message pane

(4) If the sent message appears in the thread in the message pane before finishing Quick Move, the Quick Move popup disappears

This can be problematic when the next keys typed - which are intended for the Quick Move popup - invoke some action on the selected message, such as archiving it.

This is with Thunderbird 128.5.2esr on a Mac.

**Comment by kewisch** [comment]
This sounds very much like a Thunderbird issue indeed. I suspect the selection gets changed in some way, which causes a new message to be displayed, which causes the header view to redraw and the popup to close. There isn't anything in the standard API I could trigger to change this behavior.

**Comment by billsacks** [comment]
Okay, fair enough. I appreciate your reply!
