### ISSUE TITLE
Sort results by currently selected account

### ISSUE THREAD

**Issue by sebokopter** [kewisch/quickmove-extension#2]
First: Thx for this great extension. I use it a lot.

I've set up multiple e-mail accounts in Thunderbird. When I use quickmove I always want to move a mail from one to another folder both belonging to the same account. 
Quickmove lists all available folders also from all other accounts. It happens quite often to me, that I'm moving the mail into the wrong folder. Sometimes I don't even realize it and have to then to search my mail over all acounts and folders.

I have two suggestions how this could be improved:
- sort folders list so that folders of my current selected account are always on top of the list
- or only show folders of the current selected account

**Comment by helmo** [comment]
Limiting the search results to the same account could be good in some use cases, but I would also prefer to disable such a setting.

When a folder name exists in more then one account it already gets the account name added. Fo me that is clear enough.

**Comment by olaulau** [comment]
showing the full folder path (including account name) is relevant.
it can help distinguish same folder name under multiple accounts / folders.
please :-)

**Comment by kewisch** [comment]
I'm going to go with the sorting option and will provide sensible defaults plus possibly a way to disable. Thanks for the request!

**Comment by a575606** [comment]
you rock ,thanks

**Comment by kewisch** [comment]
In a2664e30d4a89abdd828e09757d4626640c1f850 I've made sure the current account gets shown first. I don't think we need to avoid showing other accounts anymore since the new version has prominent headers when the next account starts.
