### ISSUE TITLE
1.7: Problem with Addon AttachmentCount

### ISSUE THREAD

**Issue by reiba** [kewisch/quickmove-extension#20]
Thankyou for Version 1.7. of "Schnelles Nachrichtenverschieben"!
It work fine!
But: There is a collision with addon "attachment count": https://bitbucket.org/alta8888/attachmentcount/wiki/Home. 
I have TB 68.3.1 and attachment count V. 5.4.
Normally there is a column of attachment count in the messages pane.
As soon as "quickmove" is installed, the column of attachment count is gone (although attachment count is still activated).
Could you please look into that?
Thank you very much!

**Comment by kewisch** [comment]
I'm not doing anything with tree columns afaik. Maybe you could ask the author of that add-on instead? Given I'm moving away from a traditional add-on for 2.0, where there would be no such compat issues by design, I unfortunately won't be looking into this.
