### ISSUE TITLE
Tooltiptext is missing on Addon Page

### ISSUE THREAD

**Issue by neandr** [kewisch/quickmove-extension#23]
With '_locales/messages.json' the toolotiptext seems to be defined for at least 'maxRecentFolders' element ('maxRecentFolders.title'), but on the addon-manager page there is no popup for it.
On other elements like 'Standard' or on the buttons the 'tooltiptext' pops up.
Maybe a general issue with the options.js/.html on the addon-manager page?

**Comment by kewisch** [comment]
This issue is likely no longer applicable to QFM 2.0
