### ISSUE TITLE
v1.7.0 renders location widget disfunctional and Shift+G doesn't work (TB 68.4.1 ESR)

### ISSUE THREAD

**Issue by jorgk3** [kewisch/quickmove-extension#24]
v1.7.0 renders location widget disfunctional and Shift+G doesn't work (TB 68.4.1 ESR)

**Comment by kewisch** [comment]
For more context this is on Windows. I can't reproduce this on mac. Here is the screenshot Jörg provided:
![image](https://user-images.githubusercontent.com/607198/72681978-14cc6b00-3ac9-11ea-98a8-6c46858f21fe.png)
