### ISSUE TITLE
Inconsistent display of folder hierarchy

### ISSUE THREAD

**Issue by mclaborn** [kewisch/quickmove-extension#25]
Ubuntu 18.04
Quick Move 1.7.1

I have a folder "Stuff" with hierarchy Inbox/Work/Stuff.  When I first press Ctrl + M it shows up in the recent folder list as "Stuff" but when I start typing the folder name "Stuff" it shows up in that search list as "Inbox/Work/Stuff". The inconsistency between those 2 display formats (short and full path) is a bit disconcerting. I would rather have it all one way or the other. 

Certainly not a huge problem.

**Comment by kewisch** [comment]
This should be ok for Thunderbird 115, does that work for you?
