### ISSUE TITLE
What is the highest version on TB this tool works with?

### ISSUE THREAD

**Issue by mattslay** [kewisch/quickmove-extension#30]
It's not clear anywhere that I can find what is the highest version of TB this tool works with.

For instance, it does not work with ver 76 Beta, however, TB happily let me install it with no incompatibility errors.

**Comment by mneimeyer** [comment]
Thunderbird 78.1.0 explicitly disables this extension as incompatible.

**Comment by kewisch** [comment]
Thunderbird 78 support just landed and will be available on addons.thunderbird.net in the next few days. See version 1.8.0 and up.
