### ISSUE TITLE
Make hotkeys configurable

### ISSUE THREAD

**Issue by Cito** [kewisch/quickmove-extension#36]
It would be nice if the hotkeys (Shift + M/Y/G) would be configurable so that I could use the [Nostalgy](http://alain.frisch.fr/info/ABOUT_NOSTALGY.html) hotkeys (G/S/B/C) which I'm accustomed to and which I like because they work without having to press the Shift key.

**Comment by suskozaver** [comment]
Level 2: with predefined folders also maybe? :-)

**Comment by Olifair** [comment]
I agree that it would be great if the hotkeys could be configured. shift + M seems logic for "Move", however when I have my right hand on the mouse, shift+M is not doable with my left hand. Clicking on S/G/B/C , even with shift, would be

**Comment by Olifair** [comment]
I agree that it would be great if the hotkeys could be configured. shift + M seems logic for "Move", however when I have my right hand on the mouse, shift+M is not doable with my left hand. Clicking on S/G/B/C , even with shift, would be easier. 
It would also great to have a hotkey to go back to to the last Inbox, after G has been used. thanks for considering these improvements.

**Comment by rweigle** [comment]
As a former nostalgy user I'm very much in favor of this Issue.

**Comment by rmmbr** [comment]
I agree very much with the comments in this issue and don't want only to click on "thumbs up emoji" in the other entries. I have switched from Nostalgy to QFM some weeks ago and I can hardly  emphasize that [Shift] + [m|y|g] isn't very convenient ...

**Comment by kewisch** [comment]
This is somewhat planned for the 2.0 version that should be a pure WebExtension. It will use the `commands` API, and those can be configured. We just need to find a more flexible way to do command keys in Thunderbird since we don't want to be limited in the same way Firefox does.

In the meanwhile the only option to do this is to edit the sources, there is a <key> element being injected that has modifiers:  

https://github.com/kewisch/quickmove-extension/blob/master/src/api/quickmove.js#L79

**Comment by rmmbr** [comment]
@kewisch Is it possible to give a approximate point in time for this release/functionality?

I ask, because the functionality would be a very, very great enhancement ...

**Comment by RealRaven2000** [comment]
> @kewisch Is it possible to give a approximate point in time for this release/functionality?
> 
> I ask, because the functionality would be a very, very great enhancement ...

If you would like - you could also try the quickMove feature in QuickFolders Pro which has an option to configure these without Shift. There is an additional command to skip to the next unread folder without having to have read all emails in the current one plus support for accessing subfolders via "/". Disclaimer: The keyboard shortcuts are part of the QF Pro license so if you would like to test drive, hit me up for a free test license.

**Comment by kewisch** [comment]
This works now using Thunderbird's shortcuts manager. It won't allow all buttons, but that is a limitation of Thunderbird. Please file a bug there to allow more buttons.
