### ISSUE TITLE
Goto Unified Inbox/Sent/Archives/Trash/Junk etc. Folders

### ISSUE THREAD

**Issue by CheariX** [kewisch/quickmove-extension#37]
I use [unified  folders](https://www.teamoutpost.com/blog/does-thunderbird-have-a-unified-inbox-for-teams/) (TB68).

If I press `Shift+G`, i can only switch to `Inbox - Account 1` or `Inbox - Account 2`.

It would be very nice, if the unified `Inbox` would also be available in the *goto* menu.

The same holds for other unified folders, such as Sent/Archives/Trash/Junk.

**Comment by kewisch** [comment]
Unfortunately not supported by Thunderbird's APIs. Needs https://bugzilla.mozilla.org/show_bug.cgi?id=1771860 fixed.

**Comment by CheariX** [comment]
Too bad. Thanks for the clarification.

**Comment by kewisch** [comment]
@CheariX Can you check again if this is working in Thunderbird 128? Apparently it is fixed since Thunderbird 121

**Comment by kewisch** [comment]
[quick_folder_move-3.0.0pre.zip](https://github.com/user-attachments/files/17966622/quick_folder_move-3.0.0pre.zip)

This version specifically allows you to go to unified folders, let me know if this works as expected.

**Comment by kewisch** [comment]
Assuming this works, let me know if that changes :)
