### ISSUE TITLE
Folder list displayed in single line when search results too long

### ISSUE THREAD

**Issue by ThomGr** [kewisch/quickmove-extension#38]
When searching with SHIFT-G for a common term in my folders (e.g. just a few letters, but also something like "201" where all years 201? are matched, the results list snaps to a single line. This is still usable in principle by scrolling and resizes to usable size once the results are narrowed down, but is still unexpected behaviour. 
With SHIFT-M, the behaviour is different, but the location of the popup-menu jumps around depending on length of results list: if scrolling is required, it moves to the vertical center of the screen, if scrolling is not required it jumps to the location of the message it was invoked on.
![grafik](https://user-images.githubusercontent.com/27725313/94036286-6fd70000-fdc4-11ea-817f-a572c7179013.png)

**Comment by kewisch** [comment]
Scrolling is a bit more static in v2, I believe this is fixed. Please open a new issue if not. Thanks for reporting!
