### ISSUE TITLE
Arrow up should move highlight to bottom of list of results

### ISSUE THREAD

**Issue by ThomGr** [kewisch/quickmove-extension#39]
When the result of a search operation is a long list, it would be convenient to not only be able to move the highlight through the list with arrow down key from the top, but also to be able to use arrow up key to start from the bottom. This saves a lot of key strokes! 

Thanks, Thomas

**Comment by rmmbr** [comment]
Workaround: first use the arrow down key and then use arrow up key ... Not convenient but a workaround.

**Comment by kewisch** [comment]
Fixed in 38d4625f8968a3a1feb427614207daed9cd5e2e0
