### ISSUE TITLE
Option to exclude some folders

### ISSUE THREAD

**Issue by PaysPlat** [kewisch/quickmove-extension#4]
Hello,
Can you add an option to exclude some folders in suggestions menu ?

My workcase is : I have many folders in hierarchy grouped by years, I would only have suggestions for current year folder and subfolders. 
A simpler workaround could be exclude Archive folder.

Thank you in advance for taking into account my proposal.

**Comment by kewisch** [comment]
Yes, I think excluding the archive folder by default makes sense. An option for excluding more folders might work as well, but is a little more complicated.

**Comment by RealRaven2000** [comment]
To note, the QuickFolders Add-on also has an option to omit folders from its quickMove / quickJump functionality, if you like a look. It is tied to "advanced tab properties" and so it's not stored within folder properties. Per interest, where would you store it (@Kewisch} ?
I was storing custom icon rules in the folder tree before but it wasn't always super stable; not quite sure how (or where) Thunderbird stores these internally.

**Comment by kewisch** [comment]
This would be in messenger.storage.local, as it is moving to a MailExtension

**Comment by PaysPlat** [comment]
> To note, the QuickFolders Add-on also has an option to omit folders from its quickMove / quickJump functionality, if you like a look. It is tied to "advanced tab properties" and so it's not stored within folder properties. Per interest, where would you store it (@kewisch} ?
> I was storing custom icon rules in the folder tree before but it wasn't always super stable; not quite sure how (or where) Thunderbird stores these internally.

Thank you for your suggestion @RealRaven2000. Without offense, I prefer QuickMove which fits exactly my needs in simplest way. And it is free :)

**Comment by tonycanike** [comment]
Yes, excluding the Archives folder would be a wonderful enhancement.   I use Thunderbird's archive function ("A") with the yearly option.  So for most of my active folders, I have 5 or 10 or even 23 copies of the folder within the Archives folder. (Archives/1998/Inbox, Archives/1999/Inbox, Archives/2000/Inbox,...Archives/2020/Inbox).    All those folders get in the way when I'm trying to move a message. 

Thanks!!

**Comment by PaysPlat** [comment]
Hi @tonycanike , this feature is essential for my usage, like yours.
I have implemented it on a fork and have submitted a pull request to @kewisch.
Waiting for it, you can get and use my version here https://github.com/PaysPlat/quickmove-extension/tree/feature/excludeArchives.

**Comment by dahjelle** [comment]
Another related use case: I have some personal mail accounts and some shared mail accounts. Most of the time this is not a problem, but if the shared box has a similar folder, I can accidentally file my personal mail into one of the shared folders. Allowing me to omit folders (or accounts!) would be a great solution!

**Comment by kewisch** [comment]
Exclude archives is implemented in the upcoming 2.6, excluding folders is not. Also though, the current account is always on top, so you'd more likely to move it into a folder within the same account. Leaving this open for being able to define a custom set of folders/accounts to exclude.

**Comment by dahjelle** [comment]
> Also though, the current account is always on top, so you'd more likely to move it into a folder within the same account.

That hasn't been my experience. Am I missing something? The folders seem to appear in the same order that they do in the "All Folders" pane. Am I just on an older version? You mentioned upcoming 2.6, but Thunderbird is reporting that I have 2.0.1 from July 19 installed.

**Comment by kewisch** [comment]
Yes, 2.6 is not released yet, hope to do that in the next week. Working out some bugs. Testing in #88 greatly appreciated.

**Comment by kewisch** [comment]
[quick_folder_move-3.0.0pre.zip](https://github.com/user-attachments/files/17966613/quick_folder_move-3.0.0pre.zip)

Here is a version that has preferences to exclude folders. Let me know if this works as expected?

**Comment by kewisch** [comment]
Assuming this works, so far it does for me :) Let me know if any issues comes up.

**Comment by bbceg** [comment]
Thanks very much for this @kewisch.

I'm afraid I haven't had a chance to test it out because I'm still struggling along with Thunderbird v115 while I wait for #16 to be resolved. I realise this is largely out of your hands although I wonder if one of @ThomGr's suggestions might be worth a look? 🙏
