### ISSUE TITLE
Folder sort during search

### ISSUE THREAD

**Issue by isoboroff** [kewisch/quickmove-extension#40]
In the move popup, the default folder sort is most-recently-used.  However, if you start to type, it gives search matches, which seem to be in alphabetical order.  I humbly request that this might be even more useful if the sort is also most-recently-used.

I think I know how to implement this: in src/content/quickmove.js, line 327, we can sort the list using `folders.sort(sorter)`.  However, I don't know how to test this myself as I don't have a Thunderbird plugin development setup yet.

**Comment by isoboroff** [comment]
I think I've confirmed that this simple edit doesn't work, the list that you get from typeahead is empty.  I'll poke more as time permits.

**Comment by kewisch** [comment]
You don't need anything special for add-on development. Simply editing the xpi file and then installing over should be fine, you may need to restart inbetween. If you want to build/run from the github repo you can use `npm run build` to create `dist/quickmove.xpi`

**Comment by kewisch** [comment]
Unfortunately the new Thunderbird API does not support getting the MRU time, so I'm going to have to close this issue. You are welcome to file a Thunderbird issue to add this, and when that has been fixed file a new issue here to add the feature. You'll want to file a bug mentioning the `MessageProperties` should have a mru time member.
