### ISSUE TITLE
Move is canceled when hitting enter too quickly

### ISSUE THREAD

**Issue by hamkins** [kewisch/quickmove-extension#41]
v1.8.2

When I type shift-M, then a folder name, then enter, the move is not correctly executed unless I wait for the search-result folder display to come up before hitting enter. This is not an issue of the typing not making it into the text box (which is issue #13). The text does appear in the box, but it takes QFM about 0.5 seconds to search through my list of numerous folders to generate the matching list. If I hit enter before that list comes up, the "enter" will be associated with the default folder list and not the folder name I just typed.

**Comment by pspacek** [comment]
I confirm the same behavior with shift+G, I guess it has the same cause.

I just migrated from dead addon Nostalgy and this is the main difference I noticed - old Nostalgy had "instantaneous" results so I could type part of folder name and press enter without looking at the dialog.

In any case thank you very much for this add-on, it is really a productivity boost!

**Comment by kewisch** [comment]
This used to work, if the search is still executing the move action would be postponed until the search is complete. Looks like this is a regression.

**Comment by kewisch** [comment]
Can you try again in Thunderbird 115 ? Still an issue?

**Comment by hamkins** [comment]
Thanks, I don't see the problem on 115. The conditions for the issue are also not coming up as often, because the list of folders is coming up faster.

**Comment by kewisch** [comment]
Alright, thanks. If you see this issue again please feel free to open a new issue!
