### ISSUE TITLE
Display last move in TB status bar

### ISSUE THREAD

**Issue by dapimentel** [kewisch/quickmove-extension#42]
As a former user of Nostalgy, I find that having the last know target folder displayed in the TB status bar was useful. Often I move messages between other distractions, and having such a memory aid is useful.

**Comment by kewisch** [comment]
MailExtensions will not have an API to add things to the status bar, so unfortunately I won't be working on this issue. If someone wants to contribute this as an (optional, disabled by default) feature for the legacy extension versions 1.x then I'm happy to review. Thank you for filing the issue!
