### ISSUE TITLE
Support of tag management

### ISSUE THREAD

**Issue by damiencourousse** [kewisch/quickmove-extension#44]
This extension is sometimes mentioned as a replacement of the Nostalgy or Nostalgy++ TB add-ons.
QuickMove could be a serious alternative if the management of tags was also supported.

I don't know if this is included in your plans / roadmap.  This does not seem to be mentionned in the issues so far, so I was asking, just in case.

**Comment by RealRaven2000** [comment]
how would tags be involved with moving / copying mail? I am asking as QuickFolders also has that (quickMove) functionality and might learn something valuable here.

**Comment by damiencourousse** [comment]
Managing tags is part of my workflow for processing mails.  Currently, TB can assign ten key shortcuts (keys 0..9) to tags, but this strongly limits the number of tags used.   I currently use a lot of tags, and the ability to quickly tag mails from the keyboard, without reaching the mouse, is really important for me.

**Comment by kewisch** [comment]
I like this. It shouldn't be too difficult to do, probably a bunch of copy/paste work from the current code.

**Comment by b3** [comment]
Any idea where to start if I want to try to implement this feature?

**Comment by kewisch** [comment]
There is an open function that attaches the popup to a UI element: https://github.com/kewisch/quickmove-extension/blob/main/src/content/quickmove.js#L495

then a keyboard shortcut, and the menupopup for the new tag menu: https://github.com/kewisch/quickmove-extension/blob/main/src/api/quickmove.js#L79

then you need to populate the popup when it opens using an event. Here is the one for the other folders: https://github.com/kewisch/quickmove-extension/blob/main/src/content/quickmove.js#L134

at the end there is an execute function that needs to call the Thunderbird code to tag: https://github.com/kewisch/quickmove-extension/blob/main/src/content/quickmove.js#L367

Hope this helps, I'm glad to hear you are considering contributing!

**Comment by kewisch** [comment]
Fixed in 36512bab87f04491c0b3ce65bce1a86d1d8b7bed

**Comment by b3** [comment]
How can we use a version with this feature?

**Comment by kewisch** [comment]
I'm going to release this version soon, though I wanted to get a few other issues fixed before I do so. If you want to test it, you can download the sources, go to Thunderbird's "Debug Add-ons" in the tools/developer menu, then select the manifest.json file in the src folder. Or zip up the contents (not the folder itself) of the src folder, and install that as the add-on.

**Comment by b3** [comment]
Where do you store zip files for you release?

They seems not being available in the [github release pages](https://github.com/kewisch/quickmove-extension/releases).

As my thunderbird automatically updated this extension (among a lot of other things) some day ago (to version 2.0.1, which, BTW, seems not to have tag management included), I am hit by #88. I am thus willing to take the time to test a recent version (with the tag management available if possible).

**Comment by b3** [comment]
I find a way just by looking to the [tags pages](https://github.com/kewisch/quickmove-extension/tags).

Only tagged zip are available though.
