### ISSUE TITLE
folder view reset on shift+G

### ISSUE THREAD

**Issue by pspacek** [kewisch/quickmove-extension#45]
I just migrated from Nostalgy to your extension and find this behavior surprising:

Steps to reproduce:
1. Set folder view to unread: View->Folders->Unread
2. Go to a folder which is not shown in the folder pane (because it does not contain unread messages): Shift+G a_folder_without_unread_messages

Actual result:
Folder view switches to "All" (a change from "Unread")

Expected result:
Folder view setting is left untouched.

Maybe it is intentional - in that case may I suggest adding an option to settings to disable this? 

Use-case: I have lots and lots of folders which are used only as "filling cabinet" when a message was processed. Displaying them in folder pane obscures folders with unread messages, making it too easy to overlook a message filled into a folder by message filters.

Thank you for considering this change.

**Comment by kewisch** [comment]
Yes, this was intentional, I'm not sure if this can be reasonably disabled without breaking other Thunderbird code. If the folder is not visible, a folder is selected that isn't shown in the sidebar. This can be confusing because no selected folder is shown, and we'd have to check if doing so will break Thunderbird code expecting the current folder is visible.

**Comment by pspacek** [comment]
Thank you for replying!

It used to work like I describe in Nostalgy @ Thunderbird 68. I.e. switching folders did not change folder view so the user might end up without a visibly selected folder. Maybe it would easiest to just try on Thunderbird 78 and see?

I'm happy to test a code from PR, assuming I'm able to make it work (I'm not addon developer myself so I might need pointers to docs).

**Comment by kewisch** [comment]
Unfortunately with the new add-ons model I can't influence this. You might be lucky filing a bug for Thunderbird. Thanks for the suggestion!
