### ISSUE TITLE
First display of input box (on shift-M or contextual menus) takes a long time

### ISSUE THREAD

**Issue by arkanovicz** [kewisch/quickmove-extension#49]
I'm using thunderbird 68.10.0 (64-bit) and QFM 1.7.1.
I have around 3000 mbox files, that may be why. Which specific component or indexing operation may be the culprit? Is there any caching strategy applicable?
Thanks for this great tool, btw.

**Comment by kewisch** [comment]
Yeah, it is possible that some caching would speed things up. I believe there is some amount of caching already in place. I appreciate the report here, though unfortunately I don't think there is anything immediate I can do here. The new WebExtensions version that I may eventually release could do better here.
