### ISSUE TITLE
TB87.0beta: Doesn't show folders while typing

### ISSUE THREAD

**Issue by maherma-adg** [kewisch/quickmove-extension#50]
After update to TB87.0beta, move mails doesn't work because target folders aren't show while typing.

**Comment by jpyllman** [comment]
I tried in TB89.0b1 and it does not work there ether.

**Comment by jpyllman** [comment]
@kewisch do you know if the 'old' plugins will still work with TB91? Or should we look into getting the web extensions version functional and ready??

**Comment by maherma-adg** [comment]
As far as I can see, there is a problem with the method to enumerate folders, and it's related with plugin old API
I found a add-on called Autofile, able to enum all folders without problems on TB89.0b3, sadly it doesn't met my use case

**Comment by jpyllman** [comment]
When I look more in the log there is this error about fixIterator() is not a valid anymore. And when looking around in bugzilla it looks like fixIterator is something that is getting removed. The question then is how to loop the accounts instead of using fixIterator.

**Comment by jpyllman** [comment]
https://developer.thunderbird.net/add-ons/updating/tb91/changes seem to be a good place to look for this. fixIterator() is not needed since MailServices.accounts.accounts does return a simple array.

I have made some more changes to my local copy and now this works. The main thing is better support/use of javascript arrays instead of nsIArray as mentioned in the link above. I will take a deeper look at this and send in a PR for this.

Short story, I have a fix for this.

**Comment by mbehrisch** [comment]
Would be cool to see an update of this extension. I loved it!

**Comment by MLopez-Ibanez** [comment]
> https://developer.thunderbird.net/add-ons/updating/tb91/changes seem to be a good place to look for this. fixIterator() is not needed since MailServices.accounts.accounts does return a simple array.
> 
> I have made some more changes to my local copy and now this works. The main thing is better support/use of javascript arrays instead of nsIArray as mentioned in the link above. I will take a deeper look at this and send in a PR for this.
> 
> Short story, I have a fix for this.

I would say: send a pull request, however, there are several unmerged pull requests and patches for various fixes in different forks. It would be nice to have a "main" fork or "integration" fork that combined all those fixes. From that, @kewisch could have more confidence that the various fixes work well together and are being used by more people than the original authors, hopefully getting them to the official version sooner.

**Comment by jpyllman** [comment]
When it comes to the PRs that are available, 3 is 'automatic' changes that are still valid and easy to just merge. One is my PR for this issue. And one PR is for some option changes. And there are two more from me that is more testing the fork where change this plugin to the new plugin-format. So I would say. 3 of the PRs are just merge, the 'automatic' ones. But my PR for this issue there has to be some thought if you need to support older versions of Thunderbird. The changes should be valid from version 75/76 of Thunderbird. And the new options I have not looked at.

**Comment by MLopez-Ibanez** [comment]
It is just not possible to support multiple versions of thunderbird in the same add-on. Major releases do not keep backwards compatibility and one would end up with untested spaghetti code. The most one can expect is having 2 branches, one that tracks the beta version and has the latest code and another branch that tracks the latest stable release of TB and maybe receives backports.

**Comment by zdposter** [comment]
@kewisch : is there any plan to make release that will fix this issue?

**Comment by nursoda** [comment]
Since TB91 is released, now would be a good time to provide a PR or a fork, because in some weeks, all TB78 users will auto-update to 91.

**Comment by jpyllman** [comment]
There is a PR and have existed for a long time.

**Comment by zdposter** [comment]
@jpyllman : thanks it works for me... Maybe you can make alternative release with other PRs?
Here is fixed extension without other changes (no version changes) for users that are not familiar, how to make change:
[quickmove@mozilla.kewis.ch.xpi.zip](https://github.com/kewisch/quickmove-extension/files/7000588/quickmove%40mozilla.kewis.ch.xpi.zip)
Just remove ".zip" from filename.

**Comment by jpyllman** [comment]
Yes, would be nice to put the other PRs in the same. I will see if I can make a 'combo' PR in the coming days.

**Comment by nursoda** [comment]
[quickmove@mozilla.kewis.ch.xpi.zip](https://github.com/kewisch/quickmove-extension/files/7000588/quickmove%40mozilla.kewis.ch.xpi.zip) works for me in 91.0.1 – THANKS!

**Comment by kewisch** [comment]
New version 1.10.0 is on ATN for review, should be out soon. Thank you everyone for the investigation!
