### ISSUE TITLE
Support for dark theme in webextensions

### ISSUE THREAD

**Issue by jpyllman** [kewisch/quickmove-extension#6]
I have been testing the 2.0pre1 version. The webextensions version. And the biggest 'thing' I see at the moment is that the popup menu does not follow the OS or Thunderbird theme settings. I like darkt themes, that mean white text. And since the popup stay white even in dark mode it is white text on white background in the input field.

Just wanted you to know.

**Comment by jpyllman** [comment]
I found this on mozilla web. https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by jpyllman** [comment]
This patch is by no means the final way you want it to look. But now at least it works on both light and dark themes.

**Comment by kewisch** [comment]
Dark mode is supported in v2, using the special dark mode icons from Thunderbird \o/

**Comment by jpyllman** [comment]
Yes, I see, it looks great in TB115. Thanks.
