### ISSUE TITLE
Cannot enter space in Move search bar

### ISSUE THREAD

**Issue by owen-yang** [kewisch/quickmove-extension#60]
When searching for a folder in the Move search bar (Shift-M), I cannot enter a space character, and thus cannot search specifically for folders that contain a space. This doesn't appear to be an issue with the Goto (Shift-G) and Copy (Shift-Y) search bars.

**Comment by rmmbr** [comment]
@owen-yang : I can't reproduce that on my system. W10 20H2 64 bit, TB 91.3.0, QFM 1.10.0.

**Comment by owen-yang** [comment]
@rmmbr hmm, I also can't reproduce it anymore now on W10 21h1 64-bit, TB 91.3.0, QFM 1.10.0. I should've included more info in my original post.

Will close for now.
