### ISSUE TITLE
No Work with TB 91.2

### ISSUE THREAD

**Issue by TurboDuke77** [kewisch/quickmove-extension#63]
With the new Thunderbird version 91.2 distributed via update, the Move menu no longer works. No entries of the last moved emails are displayed.

**Comment by rmmbr** [comment]
@TurboDuke77 : No problems on my system: W10 20H2 64 bit, TB 91.2.1. Has the Add-on auto-updated from version 1.9.0 to 1.10.0 on your system? If no check manualy from the TB menu.

**Comment by TurboDuke77** [comment]
Thanks, version 1.10 fixes the problem!

**Comment by rmmbr** [comment]
@TurboDuke77: If all is fixed for you, you can close the issue ... Thanks.
