### ISSUE TITLE
Allow moving through list with Tab/Shift+Tab

### ISSUE THREAD

**Issue by majutsushi** [kewisch/quickmove-extension#64]
It would be great if you could move through the pop-up list with the Tab and Shift+Tab keys instead of just the arrow keys, this way you wouldn't have to constantly move your hand to the arrow keys just to press Down once or twice. It would be even better if in addition to this the top-most entry would be automatically selected so often you wouldn't even have to move the selection at all. Thanks!

**Comment by owen-yang** [comment]
FYI, even though the top-most entry is not automatically *highlighted* when a list pops up, you can actually hit enter and the top-most entry is used. And the same is true even if you've typed something into the search box.

Agree with you that Tab and Shift+Tab would be nice.

**Comment by majutsushi** [comment]
Interesting, I never realized that that worked, thanks for the tip! I could have sworn that I must have pressed Enter at least once accidentally and not have it work. Having the first entry be highlighted would make this more intuitive, but it being possible at all makes things a lot more convenient.

**Comment by kewisch** [comment]
I've added Tab and Shift+Tab in 38d4625f8968a3a1feb427614207daed9cd5e2e0. I believe auto-highlighting the first entry will add some extra complexity or make further navigation a bit awkward. I'd be open to a patch here, but I'd rather leave it as is for now.
