### ISSUE TITLE
Move/Copy menu does not appear on MacOs

### ISSUE THREAD

**Issue by alkaphreak** [kewisch/quickmove-extension#66]
I'm using the same setup on my Linux desktop and it's working flawlessly.

MacOs: Monterey 12.1
Thunderbird: 91.4.1

**Comment by reagle** [comment]
Is this the same problem as #78 ? Please have a look at that screenshot and let me know.

**Comment by kewisch** [comment]
Please try again on Thunderbird 115, this should work more reliably
