### ISSUE TITLE
Moving an item causes previous focus to be lost

### ISSUE THREAD

**Issue by wshanks** [kewisch/quickmove-extension#67]
When I use `shift+M` and then select a folder to move an item into, I find that the previous focus in the Thunderbird UI is sometimes lost. I can most reliably get the focus to be lost by tabbing away from the message list and then using `shift+M`. Usually when the message list has focus, it keeps it. I thought I had seen the message list lose focus as well during regular use but I can't reproduce that behavior purposefully. After `shift+M` with something other than the message list focused, `tab` does not seem to focus anything. The only way I can get focus back is by using `ctrl+K` to focus the search bar and then tabbing away from there.

It would be nice if the extension could restore focus to an element after performing the move and hiding the popup so that tab could work again.

Some background: I don't actually use tab to navigate. I use [tbkeys](https://github.com/wshanks/tbkeys). When the focus disappears and tab stops working, my `j`/`k` shortcuts in tbkeys for focusing the next/previous message also stop working. Also the built in shortcuts like `b`/`f`/`p`/`n` stop working as well. It would be great if anything in the UI could be focused so that these shortcuts would keep working.

**Comment by kewisch** [comment]
This should work now in later Thunderbirds. Thanks for reporting!
