### ISSUE TITLE
Mark messages as unread when moving

### ISSUE THREAD

**Issue by lamyergeier** [kewisch/quickmove-extension#69]
There is a option for: `Mark messages as read when moving`
Is it possible to add another option for `Mark messages as unread when moving`.

This is useful as I quickly move messages to folders categorized as today, this week and later. I want them to be unread, so that I can see the count of unread messages!

**Comment by kewisch** [comment]
As a workaround you could leave the option disabled and then before moving make sure it is marked unread. Thunderbird also has an option to delay making a message unread by adjustable seconds, this in combination should solve it.

Does this help?
