### ISSUE TITLE
How to let Quick Folder Move not show the 15 most recent folders but 15 pre-defined folders?

### ISSUE THREAD

**Issue by pstein** [kewisch/quickmove-extension#72]
By default Quick Folder Move shows the 15 most recently used message folders in message "Move to" context menu.

Instead I prefer to see 15 (or less/more) pre-defined, customized folders.

How can I achieve this?

If this is not possible: Can this feature be added?

**Comment by RealRaven2000** [comment]
If you want your favorite folders, and in case its not possible with quickmove, you might want to also look into the Add-on QuickFolders...

**Comment by kewisch** [comment]
Fixed in 0ce381c1231b6e69eb57c124c9b51d8afc64db75
