### ISSUE TITLE
How to ALWAYS append the account name to the target folder in "Move to" context menu?

### ISSUE THREAD

**Issue by pstein** [kewisch/quickmove-extension#73]
I have here up to 8 different accounts defined in Thunderbird.

When I right-click on a message and open "Move to " context menu it shows  most recently folder names sometimes but not always WITH the corresponding account name.

On what criteria does it depend whether the account name is appended or not?

Sometimes I see simply "Sent". But which "Sent" folder from which account is meant?

Can I setup Quick Folder Move so that ALWAYS the account name is appended?

If this is currently not possible: Can this feature be added in the next release?

Thank you

**Comment by kewisch** [comment]
This should be more apparent in version 2 on Thunderbird 115. please crea new issue if not :)
