### ISSUE TITLE
Menu seriously slowed down after updating to Thunderbird version 102.1.0

### ISSUE THREAD

**Issue by KC-T** [kewisch/quickmove-extension#76]
Thunderbird version 102.1.0 itself has been slow and can freeze easily.

After upgrading to Thunderbird version 102.1.0, Quick Folder Move's context menu takes a very long time to list the folders. This greatly reduces the usefulness of Quick Folder Move.

**Comment by sethrichards** [comment]
I'm getting similar behavior, although in my case it's usually a relatively brief pause (a second or two) before the list appears. Still enough to slow down triaging large amounts of email.

I've worked around it by setting "Number of Recent Folders" to 0 and then always using the search box to pull up a list of folders. Obviously this is more keystrokes but the responsiveness is more consistent.

**Comment by quusi** [comment]
Exactly the same here. We have several windows 10 machines here in the same network. One is as fast as before, the others are horribly slow, so that we went back to  version 91. I have no idea, what is blocking. Surely we have a lot of folders, which are all stored on our local server, and not on the local computers.

**Comment by KC-T** [comment]
I have switched back to version 91's latest update. Working fine. Unfortunately, Thunderbird says this is the last update of version 91 meaning no security fixes.

**Comment by KC-T** [comment]
I have tried Move Messages and Yourself. Fast, but its shows Account 1, 2, 3 . .. instead of actual account names. Not convenient if you have many accounts.

**Comment by RealRaven2000** [comment]
Everyone, upgrade to Thunderbird 102.2 - they fixed a bunch of stuff regarding folder iteration. It helped with my Add-on QuickFolders as well, which also needs to iterate folders like quickmove does.

**Comment by rmmbr** [comment]
Update-Info from Mozilla: Version 102.2.2, first offered to channel users on September 7, 2022
=> fixed: Accessing mail folders in profiles with many folders was slow

**Comment by RealRaven2000** [comment]
> Update-Info from Mozilla: Version 102.2.2, first offered to channel users on September 7, 2022 => fixed: Accessing mail folders in profiles with many folders was slow

nice one - does anyone have the related bug # ? I would be interested in the details of this particular fix.
