### ISSUE TITLE
Thunderbird 102.2.0: Extension not working and options screen is messed up

### ISSUE THREAD

**Issue by HarryBleckert** [kewisch/quickmove-extension#77]
Using latest Thunderbird 102.2.0 (32-bit)
![image](https://user-images.githubusercontent.com/10340436/186335993-23744823-1dfd-4ce7-9145-b8c386d652dd.png)

**Comment by sluedecke** [comment]
Looks good on my system (102.2.0 (64-bit)):

![image](https://user-images.githubusercontent.com/7710530/189134146-c5ace545-8273-47b2-9d30-e7f4a625c7e5.png)


![image](https://user-images.githubusercontent.com/7710530/189133953-94f6ea6b-4a2d-47cf-a2b0-d27af589cd76.png)

**Comment by HarryBleckert** [comment]
Now using 102.3.3 (64-bit).  Problem prevails. Extension not working at all. No debug info.

**Comment by kewisch** [comment]
Can you try version 2 on Thunderbird 115?

**Comment by kewisch** [comment]
Actually I am going to go ahead and close this, I'm pretty certain this will work in version 2. Do file a  new issue if not please!
