### ISSUE TITLE
Context menu popup is empty

### ISSUE THREAD

**Issue by reagle** [kewisch/quickmove-extension#78]
Running plugin version 1.10.0 on 102.2.2 (64-bit) on macOS 12.6 21G115 arm64. When I alt-click on a message to move it via popup, no options are given.

![SCR-20220915-cwc](https://user-images.githubusercontent.com/596814/190413954-09a90208-2aa4-4171-9d76-9657e9106163.png)

![SCR-20220915-cwq](https://user-images.githubusercontent.com/596814/190413968-9152ee7d-d7d6-4fd8-937b-b187c9a1813f.png)

**Comment by kewisch** [comment]
Can you try again on Thunderbird 115 and v2?

**Comment by kewisch** [comment]
Ah sorry, misread. The new version doesn't support the context menu entry anymore unfortunately
