### ISSUE TITLE
"Exclude Archives folder from search results" not working

### ISSUE THREAD

**Issue by bbceg** [kewisch/quickmove-extension#79]
I was delighted to discover this feature today but quickly disappointed when I found it didn't work.

I have Archives > Local Folders > Old Clients > Client A, Client B etc and these still show on searching when this option is selected.

I'm running the latest stable version (102.3.3).

Do let me know if I'm missing something or if there is anything I can do to help troubleshoot.

**Comment by kewisch** [comment]
It is not easier, unfortunately. Some time in the future I might include a view options button right within the popup, but that would require some more refactoring that I'm not inclined to right now. The return of excluding archive folders will be available soon, I've fixed this in 3b866b78c16b8c9970a3dd26eb5bfd08e16476a4.

**Comment by bbceg** [comment]
No problem, thanks for considering and for resolving the more general issue.
