### ISSUE TITLE
Mouse hover over list of folders takes away focus from search

### ISSUE THREAD

**Issue by jpyllman** [kewisch/quickmove-extension#8]
In the webextension version. If the mouse pointer happens to be where the list of folders are it will take away the focus from where you enter your search. This often makes me do unknown things to the messages in the folder I was trying messages from.

**Comment by jpyllman** [comment]
OK, I found where the .focus() that do this. Commenting it out does not seem to break anything. I might do a pull request for this.

**Comment by kewisch** [comment]
Would appreciate a PR! It is likely I added the focus to make the menuitem "selected" from an accessibility perspective, and so that using the keys will move the selected item accoridingly. If that still works without focus() it would be great.

**Comment by jpyllman** [comment]
OK, when I remove the focus() part I can still move around with the keys. But if I have it there it will steal focus from the search field.

**Comment by kewisch** [comment]
Fixed in 5cf34772179eeffebe326106a72b0203ff97f18b

**Comment by kewisch** [comment]
Releasing versions to addons.thunderbird.net is manual. I'll push one out soon, but wanted to fix a few of the other issues first.
