### ISSUE TITLE
Add a feature to quickly add tag(s) to messages

### ISSUE THREAD

**Issue by b3** [kewisch/quickmove-extension#80]
I do not know if it this could be difficult or if it is the right place to ask, but it would be great to add a feature very close to the quick move: the ability to quickly tag a message the same way we quickly move them.

**Comment by rmmbr** [comment]
Same as [https://github.com/kewisch/quickmove-extension/issues/44](url)?

**Comment by b3** [comment]
It can be considered that way, definitively.
