### ISSUE TITLE
Search field is missing

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [kewisch/quickmove-extension#85]
Hi Philipp,

How are you doing?

I just switched to Win 10, & now on TB the quick folders search field is missing. I'm on 102.10.0

I turned off all of my other extensions & restarted TB & nothing. :(

Please help.

Thanks 

P.S. I tried to DM you on Twitter & it kept failing.

**Comment by kewisch** [comment]
Hey, please try out the new version on Thunderbird 115 :)
