### ISSUE TITLE
Enhancement Request - User Selectable Keyboard Shortcut Key Combos

### ISSUE THREAD

**Issue by DarkAthena** [kewisch/quickmove-extension#86]
Just starting out with Thunderbird and would love to be able to set the key combo to the same at my work Outlook and MsgFiler for Apple Mail. I can't change the Outlook key combo because Microsoft. 

Thanks for the consideration.

**Comment by rmmbr** [comment]
@DarkAthena: If I understand you correctly your request is duplicated to [https://github.com/kewisch/quickmove-extension/issues/36](url). I also hope that there will be an implementation for this ...

**Comment by kewisch** [comment]
You can do this in Thunderbird's shortcuts manager, though there are some limitations on which keys are allowed.
