### ISSUE TITLE
Changes for Thunderbird 115

### ISSUE THREAD

**Issue by Betterbird** [kewisch/quickmove-extension#87]
A lot of changes will be required to make the add-on work in TB 115. We did an initial investigation. With the attached patch based on https://github.com/kewisch/quickmove-extension/commit/1774546923c4667fc93096a6ff4e3a04a6269bec, the following works:
1. Shift+M, not perfect, pop-up not opened at the right position.
2. Context menu "Move To" and "Copy To". This needs a restart after add-on installation with the 3pane opened.
3. The folder location widget.

Feel free to use our work with some attribution, like: "Initial investigation by the Betterbird Project", or "Parts of the changes by the Betterbird Project".

[qfm115.diff.txt](https://github.com/kewisch/quickmove-extension/files/11512005/qfm115.diff.txt)

**Comment by Betterbird** [comment]
Updated.
[qfm115.diff-2.txt](https://github.com/kewisch/quickmove-extension/files/11643307/qfm115.diff-2.txt)

**Comment by Betterbird** [comment]
Looks like the add-on has been completely reworked and the suggested changes are no longer necessary.

**Comment by tuxayo** [comment]
@Betterbird are you sure? It's still not listed as compatible with 115: https://addons.thunderbird.net/en-US/thunderbird/addon/quick-folder-move/

**Comment by RealRaven2000** [comment]
it's here:
https://addons.thunderbird.net/en-US/thunderbird/addon/quick-folder-move/versions/?page=1#version-2.0.1
ATN  has some annoying bugs regarding  that manifest when addon authors release new versions that break backwards compatibility. 

these usually show up during ESR changeover. (115 isn't pushed to the public via automatic updates) also the search within Thunderbird Add-ons Manager is borked: it only shows the chronologically last Addon and may hide a compatible version on your particular version.

workaround: visit the site with a Web browser and click on the other versions link.
