### ISSUE TITLE
Cannot start typing with new context menu depending on mouse location

### ISSUE THREAD

**Issue by cegfault** [kewisch/quickmove-extension#89]
The new context menu is significantly larger; if Shift+G or Ctrl+Shift+G is pressed, the new context menu appears; however it is so large that my mouse is frequently in the area where the menu appears. The consequence is that the mouse is appeared to "hover" over a recent folder.

In other words:
Old Context Menu: Shift+G, menu appears, start typing, folder list appears below
New Context Menu: Shift+G, menu appears, if the mouse is over the window then typing does nothing; move mouse back to search window, click, start typing, folder list appears below.

This is incredibly frustrating. I have to intentionally move my mouse off-screen before using the shortcut, which defeats (for me) the purpose of having this extension. About 80% of the time my mouse is in the way.

Steps to reproduce:
- press Shift+G
- notice where the context menu appears
- close context menu
- move mouse into the area where the context menu was
- press Shift+G again
- observe that typing has no effect; the mouse location has "selected" a folder

Possible solutions:
- make the context menu smaller again (or allow this as an option)
- enforce that typing on the keyboard updates the context menu, even if the mouse is hover over a folder

**Comment by Cito** [comment]
I like the large menu, but I also noticed this problem. What makes it even worse is that typing does not have no effect, but sometimes even sends the keystrokes to the application. E.g. when I quickly press Shift-G and then the letter A, the mail gets archived.

**Comment by cegfault** [comment]
I very much prefer the smaller popup (personal preferences), so I'd be okay with it simply being made smaller again. However, I'd agree that regardless of size this is definitely a bug so a solution would be better than changing the size.

**Comment by cegfault** [comment]
Update: I verified on a previous version that the smaller context menu did *not* have this issue. That is, if I place the mouse in the area it does **not** automatically select/hover the entry.

In other words, this *should* be possible so solve without making the popup small again.

**Comment by christophjahn** [comment]
The same issue affects the moving of mails (Shift-M). At least I now know how to avoid it. But I have to agree with @cegfault in the frustration. I also happen to prefer the smaller menu (esp. if working on a laptop with a 13" screen).

But let me also express my gratitude for this wonderful plugin. It has made my life so much easier and I miss something like it every day when I use Outlook for work.

**Comment by kewisch** [comment]
The new version is a complete rewrite using different tech, so I can't simply do it the old way unfortunately. 

I may have limited possibilities here, but will check if there are any immediate remedies.

**Comment by kewisch** [comment]
I added a compact layout in ec1ab7c78099db7c1ace5906960bec1988cb313a which might be a good start, will look at the rest later.

**Comment by kewisch** [comment]
And now I added 5cf34772179eeffebe326106a72b0203ff97f18b which will not focus until the mouse has been moved. This should finally fix the issues described. There are options for both the wide and the narrow layout. Everyone wins :)
