### ISSUE TITLE
v1.7.0pre1 shift+M does not work?

### ISSUE THREAD

**Issue by kwoot** [kewisch/quickmove-extension#9]
Using thunderbird 68.1.2 (64-bit) on Ubuntu Linux. Click on message, press ctrl+M. No respons from Thunderbird.

**Comment by kewisch** [comment]
Error console messages? Are you able to check the main window in devtools to see if there is a `<key>` element for quickmove?

**Comment by kwoot** [comment]
Hi!
Not really. Simply pressing ctrl-M does not do anything in the console.
Down here I select your own v1.7.0pre1 notification message:

XUL box for statusbarpanel element contained an inline #text child, forcing all its children to be wrapped in a block. 3 messenger.xul
XUL box for statusbarpanel element contained an inline #text child, forcing all its children to be 
wrapped in a block. mailWidgets.js:986:29
XHRPOSThttp://127.0.0.1:4223/ja/0.1/callFunction
[HTTP/1.1 200  377ms]

XUL box for statusbarpanel element contained an inline #text child, forcing all its children to be wrapped in a block. 2 messenger.xul
XUL box for statusbarpanel element contained an inline #text child, forcing all its children to be wrapped in a block. 2 quickfolders-interface.js:5623:33
XUL box for statusbarpanel element contained an inline #text child, forcing all its children to be wrapped in a block. 3 messenger.xul

​I doubt it is useful. If you can maybe put in a little more logging I be glad to assist in the debugging.
Regards!
Jeroen

**Comment by brackenhill-mob** [comment]
+1

**Comment by bbceg** [comment]
Is it relevant that the title of this issue contains 'shift+M' but your ticket descriptions state 'ctrl+M'? Probably not but seemed worth checking! I could not get either shortcut to work (on Windows 10, Thunderbird 68.3) but v2.0.0pre1 works when legacy shortcuts are disabled.

**Comment by grubers** [comment]
I am experiencing the same problem on Mac (Mojave, 10.14.16) with Thunderbird 68.3.0 (64-bit) and v1.7.0pre1. "Shift+M" should bring up the "Quick Folder Move" menu (on Mac) but nothing happens. Also, no messages are displayed in the error console.

With v2.0.0pre1 all shortcuts (Shift+M, Shift+Y and Shift+G) work (after clicking "Use Legacy Shortcuts" in the Add-On settings of "Quick Folder Move").

**Comment by helmo** [comment]
An update to [v1.7.0pre2](https://github.com/kewisch/quickmove-extension/releases/tag/v1.7.0pre2) resolves this.
@kewisch please publish that to the mozilla site to be able to get it via the regular update channel.

**Comment by kewisch** [comment]
I'll publish pre2 when it is ready. I'd like to get some more testing from folks :)

**Comment by mclaborn** [comment]
Pre2 working fine for me on Ubuntu 18.04.

**Comment by grubers** [comment]
I can also confirm it working now with v1.7.0pre1 and my setup (Mac (Mojave, 10.14.16) with Thunderbird 68.3.0 (64-bit)).

**Comment by kwoot** [comment]
Confirm pre2 works for me too on Ubuntu 19.10 with TB 68.2.2. I am soooo happy now!!! Thank you, thank you!
