### ISSUE TITLE
"Show Full Path" option should show folder names inline, not on the right side

### ISSUE THREAD

**Issue by cegfault** [kewisch/quickmove-extension#90]
The preference "show full path of each folder in search box" should show the path in the main window, not on the right hand side.

The new context window shows the folder path on the right-hand side. Although this may be "cleaner", it's significantly more confusing when dealing with multiple folders which have the same name.

For example, let's pretend we have a file structure of year > month > day (for example). Searching "July" would have many folders: 2023 > July, 2022 > July, 2021 > July, etc. Right now, the search bar returns a dozen "July" folders, but path is on the right hand side.

Maybe it's a preference issue, so perhaps another option for "Show full path inline" would suffice. The prior context popup which showed "2023/July", "2022/July", etc, was easier to read. I've found the new layout to impede my workflow.

**Comment by kewisch** [comment]
I'm not sure I want to add too many options here, but what I can offer, in a recent commit I added a compact layout that is half as wide as before. If you enable this plus he option to show full path, it will show the full path inline. I'm going to spin a release soon, but you are also welcome to test from the `main` branch. Let me know if this works?

**Comment by cegfault** [comment]
I just tested from the main branch, and it's working perfectly! Fantastic work @kewisch  :)

The "automatic" option for popup layout works great, also.
