### ISSUE TITLE
Can no longer use keyboard to pop up folder list

### ISSUE THREAD

**Issue by ThePurpleGirl22** [kewisch/quickmove-extension#91]
I would still like to use Shift M or Shift G to bring up a folder list. Has that option been removed or am I missing something?

**Comment by rmmbr** [comment]
@ThePurpleGirl22 It would be helpful to know something about the versions of your system ... Thunderbird-version? Quick Folder Move-version?

**Comment by ThePurpleGirl22** [comment]
Thunderbird Version: 115.1.0

Quick move Version: 2.0.1

**Comment by Cito** [comment]
Is the option (Options -> Force use of legacy shortcuts) missing or is it just not working? For me, it's working with the same versions. However, there seems to be a problem with the *new* shortcuts: #88

**Comment by ThePurpleGirl22** [comment]
Thank you. It was there but I did not have that ticked. It is now working. I appreciate how quickly you assisted me.

**Comment by kewisch** [comment]
When you upgraded, did a page describing the changes show up? I've heard reports this was not the case.

**Comment by ThePurpleGirl22** [comment]
Thank you. I ticked the forced use of legacy shortcuts option and it worked. Deb Cantoniwww.thespace.com.auOn 7 Aug 2023, at 4:14 pm, Christoph Zwerschke ***@***.***> wrote:﻿
Is the option (Options -> Force use of legacy shortcuts) missing or is it just not working? For me, it's working with the same versions. However, there seems to be a problem with the new shortcuts: #88
