### ISSUE TITLE
[Supernova] cmd-shift-m Move message to last folder not updated by moving messages

### ISSUE THREAD

**Issue by dwt** [kewisch/quickmove-extension#92]
Before Supernova, moving messages via the extension updated the target of the menu entry "Move selected messages to last folder", making it really easy to quickly file away massive amounts of messages.

<img width="320" alt="Bildschirmfoto 2023-08-08 um 10 35 35" src="https://github.com/kewisch/quickmove-extension/assets/57199/cfc3198c-b599-47ca-b981-67862250efad">

The target of that move message menu entry is no longer updated when moving messages via the extension.

Is that a bug or is that no longer possible?

**Comment by dapimentel** [comment]
I'd also like that menu item to be updated again. Thanks.

**Comment by kewisch** [comment]
Thanks, I was not aware. I've also filed a Thunderbird bug because this should work out of the box https://bugzilla.mozilla.org/show_bug.cgi?id=1849476

**Comment by kewisch** [comment]
Will look at a few other issues and then spin a release
