### ISSUE TITLE
Quick Move doesn't work with the Addon ExQuilla for Exchange 

### ISSUE THREAD

**Issue by DscheyTi** [kewisch/quickmove-extension#93]
Hello together,
as far as ExQuilla for Exchange is activated, you only can see the Main Buttons and the search line of Quick move (see attached file).
As far as I deactivate ExQuilla for Exchange Quick Move works properly (see other attached file :)
Greets
![ExQuilla for Exchange (deaktiviert)](https://github.com/kewisch/quickmove-extension/assets/141798286/68170e91-625c-4849-95c6-cfa3bce649f8)
![ExQuilla for Exchange (aktiviert)](https://github.com/kewisch/quickmove-extension/assets/141798286/cb716fb8-aef6-46e2-b10a-de4ddbc98629)

**Comment by kewisch** [comment]
Do you get any error console messages? Since the new version almost exclusively uses the Web/MailExtensions framework, it is more likely this is an issue with Exquilla.

**Comment by DscheyTi** [comment]
There are no messages.
Exquilla deactivated.... Quick move works properly.
Exquilla activated.... Game over ;)
Greets

⁣BlueMail for Android herunterladen ​

**Comment by kewisch** [comment]
I've tried to reproduce simply by installing the add-on, to no avail. I guess I need to set it up somehow, but I believe it is paid. Can you contact their support?

**Comment by infinitelyintrigued** [comment]
I have a similar issue.
I use Owl for Office365 (https://www.beonex.com/owl/). I also have a Gmail account.
Quick Move can search through Gmail folders but not through my Outlook folders. (It only shows Inbox, Draft, and Sent Items.) Quick Move is a great time-saver for my Gmail. If it can work with Owl, that would be wonderful.
I believe Owl has a one-month free trial period.
