### ISSUE TITLE
Not Working in opened Mail Tab or Mail window

### ISSUE THREAD

**Issue by TurboDuke77** [kewisch/quickmove-extension#97]
Mails in the Inbox view can be moved without problems using the Quickmove button. If I open a mail (in a new tab) or in a new window, the move with the Quickmove button does not work.

TB 115.1.1 (Windows 64-Bit) Supernova
Quickmove 2.0.1

**Comment by jaduffus** [comment]
This is also occurring for me when I open a message (in tab or window)  in TB 115.2.0 (64-bit) macbook OSX ver.13.4 (Ventura) Ctl-Shift m or Shift-M does not move message, nothing happens, no dialog. If I close the message, only Shift-M works, Ctl-Shift-M does not.

Thank you!

**Comment by jenniedo** [comment]
This is happening for me too: I can make Quickmove work, but only in the inbox view, not when I open an email in a new window or tab.

**Comment by kewisch** [comment]
If Shift+M works and the other keys do not, check if you have the legacy shortcuts option enabled in the preferences. For the remaining noted issues, I'm going to need more info. Do you get error console messages? Can you describe "does not work" in more detail?

**Comment by jenniedo** [comment]
I'm not using any keys, I'm using the "quick move" button at the top of the Thunderbird window by moving my mouse there and clicking on it.

And n, there are no error console messages in the circumstance I described. It just doesn't do anything (i.e. doesn't move the message into the requested folder).

**Comment by kewisch** [comment]
I've fixed this in 28079457, I'll hopefully be releasing a new version this week. Please help test the issue in #88 !

**Comment by kewisch** [comment]
Actually, what I fixed was likely the original issue, not anything related to not being able to move. Can you file a separate issue on that? Is this maybe #101, or does it happen with every message? It seems to work for me, so any further details are appreciated.
