### ISSUE TITLE
don't see option page to set key mappings

### ISSUE THREAD

**Issue by pcause** [kewisch/quickmove-extension#99]
I am in 115.2.2 on Linux.  I don't see the options to define keyboard mappings for the various functions.

**Comment by rigow** [comment]
They are totally hidden. In the extension view, there is the gear on the top right. When you click on it, there is a popup. At the end of the popup, there is an entry for the shortcuts. Clicking left should get you there.

**Comment by pcause** [comment]
thanks.  got it

**Comment by kewisch** [comment]
Yeah, not great to see. Would be cool to show those in the per-extension settings as well, but you'll have to get Firefox to change that first. https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox
